### ISSUE TITLE
Decode Custom JWT

### ISSUE THREAD

**Issue by CHOMNANP** [tymondesigns/jwt-auth#1013]
I had custom format JWT sending from other application.
I would like to decode the custom JWT, so I could use the Payload inside it.
Can I use the package to decode?

Thanks.

**Comment by willgopublic** [comment]
Tymon's JWT-Auth uses Namshi's library for encoding and decoding jwt's ( \Tymon\JWTAuth\Providers\JWT\Namshi::decode ).

See https://github.com/namshi/jose for more information. In your case you perhaps extra attention is needed for https://github.com/namshi/jose#unsecure-jwses since the JWT comes from another application.

**Comment by CHOMNANP** [comment]
Hi @willgopublic,

Thank you for your guideline. It's been a while that I haven't work on this.
I have managed to get it work by following your guideline.

1. Create static method: decode3rdparty() in class Tymon\JWTAuth\Providers\JWT\NamshiAdapter

`public static function decode3rdparty($token_string)
    {
        try {
          $result =  JWS::load($token_string, true);
        } catch (Exception $e) {
            throw new TokenInvalidException('Could not decode token: '.$e->getMessage());
        }
        return $result->getPayload();
    }`

2. Calling method: 
`return Tymon\JWTAuth\Providers\JWT\NamshiAdapter::decode3rdparty($request->token);`

Thank a lot :)
