### ISSUE TITLE
Exception default status code '0' error

### ISSUE THREAD

**Issue by akkhan20** [tymondesigns/jwt-auth#1116]
i Suggest setting the default status code from 0 to anything in constructor like 522 etc in:

> Tymon\JWTAuth\Exceptions\JWTException Class 

at
`
public function __construct($message = 'An error occurred', $code = 0, Exception $previous = null)
    {
        parent::__construct($message, $code, $previous);
    } 
`
to
`public function __construct($message = 'An error occurred', $code = 522, Exception $previous = null)
    {
        parent::__construct($message, $code, $previous);
    }`
as i have faced a condition where it returned the code 0 which is invalid Http status code.

**Comment by gigmaps** [comment]
if you look in the [src code](https://github.com/tymondesigns/jwt-auth/blob/develop/src/Exceptions/InvalidClaimException.php#L28) (for develop) it doesn't actually have status codes defined
unlike the [master branch](https://github.com/tymondesigns/jwt-auth/blob/master/src/Exceptions/InvalidClaimException.php#L19) which defines a $statusCode for each exception type
...not sure why these were removed for the dev branch

also the suggested [wiki code](https://github.com/tymondesigns/jwt-auth/wiki/Authentication#laravel-5) (using `instanceof` etc) didn't work for me (Laravel 5.4 with 1.0.0beta3)
i had to use `get_class` rather than `instanceof` - again no idea why

this is the app/Exceptions/Handler.php code that worked for me (notice the manually added [status codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes))

 ```
/**
 * Render an exception into an HTTP response.
 *
 * @param  \Illuminate\Http\Request  $request
 * @param  \Exception  $exception
 * @return \Illuminate\Http\Response
 */
public function render($request, Exception $exception)
{
	$exceptionClass = get_class($exception);

	switch ($exceptionClass) {
		case 'Tymon\JWTAuth\Exceptions\TokenExpiredException':
			return response()->json(['token_expired'], 401);
			break;
		case 'Tymon\JWTAuth\Exceptions\TokenInvalidException':
			return response()->json(['token_invalid'], 401);
			break;
		case 'Tymon\JWTAuth\Exceptions\JWTException':
			return response()->json(['general JWT error'], 500);
			break;
		default:
			return response()->json([$exception->getMessage()], $exception->getStatusCode());
			break;
	}
	return parent::render($request, $exception);
}
```
