### ISSUE TITLE
Cannot Use latest release : `JTI improvement` due to  `namshi/jose` dependency

### ISSUE THREAD

**Issue by progammer-rkt** [tymondesigns/jwt-auth#1122]
Hi it seems latest release: ` JTI improvement` is not downloading due to composer is not updated with `namshi/jose` latest package. 

It currently point towards `^5.0` version. But it needs to be pointed towards `^7.0`. Please do needful.

**Comment by adamtomat** [comment]
Ran into the same conflict with `namshi/jose` when using Laravel's Passport package.

This is because `namshi/jose` at `^5.0` requires `"phpseclib/phpseclib": "~0.3"` (see https://github.com/namshi/jose/blob/5.0.2/composer.json#L24).

However Passport requires `"phpseclib/phpseclib": "^2.0"` (see https://github.com/laravel/passport/blob/v2.0.6/composer.json#L27).

This means that I am unable to install the stable version of this package.

**Comment by tymondesigns** [comment]
fixed via `0.5.12`
