### ISSUE TITLE
Does the refresh_ttl reset when the token is refreshed?

### ISSUE THREAD

**Issue by user498452** [tymondesigns/jwt-auth#1185]
For example, if I have these settings:

- `ttl => 5`
- `refresh_ttl => 60`

And the user initially logs in at `12:00`, then the token will expire at `12:05` and the user has until `13:00` to refresh the token.

If the user refreshes the token at `12:15`, does the `refresh_ttl` get reset, so that the user has until `13:15` to refresh the token, or does it stay at `13:00`?

Because currently, my code does the latter (i.e. it will stay at `13:00` regardless of whether or not the user refreshes the token before then). 

Is that normal behavior?

Here is my refresh token method:

```
public function refreshToken(Request $request)
{
    $token = JWTAuth::getToken();

    try
    {
        $newToken = JWTAuth::refresh($token);
    }
    catch (TokenExpiredException $e)
    {
        return response()->json([
            'success' => false,
            'data' => [
                'errors' => [
                    'auth_token' => [
                        'token_expired'
                    ]
                ]
            ],
        ], $e->getStatusCode());
    }
    catch (TokenInvalidException $e)
    {
        return response()->json([
            'success' => false,
            'data' => [
                'errors' => [
                    'auth_token' => [
                        'token_invalid'
                    ]
                ]
            ],
        ], $e->getStatusCode());
    }
    catch (JWTException $e)
    {
        return response()->json([
            'success' => false,
            'data' => [
                'errors' => [
                    'auth_token' => [
                        'token_absent'
                    ]
                ]
            ],
        ], $e->getStatusCode());
    }

    return response()->json([
        'success' => true,
        'data' => [
            'auth_token' => $newToken
        ],
    ], 200);
}
```

**Comment by akkhan20** [comment]
obviously it will send a new token with changed 'TTL' are you getting the new token and attaching the new token with subsequent requests?

**Comment by user498452** [comment]
Yes, I use the new token in every new request, but I think you might be confusing my question.

I'm asking if the `refresh_ttl` gets reset when the user refreshes their token?

So if the user initially logs in at `12:00` (which means that they have until `13:00` to refresh the token), and the user refreshes their token at `12:30`, does the `refresh_ttl` get set back to `13:30` or does it stay at `13:00`?

**Comment by akkhan20** [comment]
it gets to 13:30

**Comment by user498452** [comment]
Okay, then that's my problem, and I'm not sure why.

For some reason, my `refresh_ttl` doesn't get reset when the user refreshes their token.

If a user initially logs in at `12:00`, and then refreshes the token at `12:55`, they will **still** be logged out at `13:00` and the server will return `token_expired`.

@tymondesigns Any ideas why this might be happening given my code?

**Comment by tymondesigns** [comment]
@akkhan20 is incorrect. Your experience is as expected (although I can see why you would think otherwise) 

It's something I'm considering at the moment. I'm thinking of a few options. 

One of which is making the behaviour follow your example, where after a refresh, the token `iat` claim is extended and further refreshes simply extend that time frame. 

Another option is to have a totally separate refresh token, similar to OAuth2 flows where only a separate refresh_token can be used to obtain a new valid token.

Hope that answers your question

**Comment by user498452** [comment]
Thanks for the clarification.

It definitely makes more sense for the `iat` to extend after an auth token is refreshed. I'm surprised that that's not what it already does.

**Comment by user498452** [comment]
I don't really want to force my users to have to re-login unless absolutely required, so can `refresh_ttl` be set to `null`?

**Comment by tymondesigns** [comment]
@user498452 yes, you could set the `refresh_ttl` to null and your token will always be refreshable.

**Comment by hriverahdez** [comment]
So, I found this issue because I'm currently facing the same problem. At first I thought I was encountering a weird bug, but now that I've read this it makes sense. So any news on the refresh_ttl reset??. I could set to to null as suggested by @tymondesigns but the way my app is required to work is:
- Have a token ttl of 1h
- Able to refresh within a time frame of 2h, so that if the user is working with the application he will not get redirected to a lock-screen
- If the user is absent for a period over 2h (the token can't be refreshed any longer) then he is required to re-authenticate.

I'm using Angular on the frontend and the refresh endpoint and middleware is working fine, except for the issue of the cumulative refresh_ttl. 
Any ideas on a possible workaround?
