### ISSUE TITLE
Class 'Memcached' not found

### ISSUE THREAD

**Issue by robcaa** [tymondesigns/jwt-auth#1420]
Lumen: 5.5
tymon/jwt-auth: 1.0.0-rc.1

In the env file:
CACHE_DRIVER=file

This line of code:
```
$user = Auth::user();
```
sometimes produce this error:
`Class 'Memcached' not found`

Hoever I dont use memcached.

**Comment by tymondesigns** [comment]
This package does not use memcached directly, so it must be something with your setup

**Comment by robcaa** [comment]
Yes, I realized.
Thank you for your answer.

**Comment by dhcmega** [comment]
Hi @robcaa 
I have the same problem. Memcached works ok for WEB requets, but I get `Class 'Memcached' not found` for all API requests.
How did you solve your problem?
Thanks!

EDIT1: In my case the problem is that Dreamhost has php74 without memcached and php73 with memcached. It turns out that I was using php74 for api requests.
