### ISSUE TITLE
jwt.refresh not returning a new token when a FormRequest validation fails

### ISSUE THREAD

**Issue by alanmtk** [tymondesigns/jwt-auth#1446]
I'am using:
Laravel (5.3.30) 
Dingo (1.0.0-beta8)
JWT-Auth (^0.5.12)

I have an endpoint to create a new Post. This endpoints has two possible ways.

The first one, you send all the required params by the backend to create the Post so it's created and a 200 response is returned with the created Post **and the new token is returned**.

The second possible way, you DO NOT send all the required params so a 422 Unprocessable Entity response is returned with the required fields which failed BUT **without a new token to make the next request.**

I don't know if this is a bug or this is an expected behaviour (this is my first time building an API for a real project). If this is the expected behaviour how should I handle these situations?

**Comment by tymondesigns** [comment]
The reason is that Laravel will validate the request early on before it hits any other middleware or your controller method. Which means your previous token is still valid since it hasn't been invalidated yet

**Comment by victorjkhalaf** [comment]
Sorry to reopen this but with blacklist enabled our client app would effectively end up on a "timer" of however long the blacklist grace period is, and if no other calls are made in that period of time, the token will end up blacklisted because it got used once to validate.
This occurs when formrequests fail, validations fail, and when returning an error type response using Dingo.
It doesn't look like we can reliably do validations without increasing the blacklist grace period dramatically if so. Is this by design?
