### ISSUE TITLE
Question: encrypting the token - security concern

### ISSUE THREAD

**Issue by kfirba** [tymondesigns/jwt-auth#152]
Hello.

I've been playing with this for a while, unfortunately the documentation is rather poor so I had to dig-in and try to find out what's going on and what methods are available.

Are the tokens safe? If I'm planning to attempt a user login, I would like to have the token encrypted so even if a 3rd party intercept the token, they won't be able to know what was the data without some hard-to-obtain key. Is it how it is right now? (Also planning to use SSL)

As a side request, I would like to know the "flow" of the process and if possible, please add more documentation.

Thanks :+1:

**Comment by jossemarGT** [comment]
Hello! I think that you can find your answer at the wiki and the jwt specification draft.

But the short answer is a jwt token is already [encoded](https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#page-6), but as always the threat is the communication channel, because anyone who intercepts a request and extract the token. Other weak point is in the API client (your application) if that token is stored in an insecure user space.

That being said is a good idea to use SSL and encrypt your storage artifact (like your cookies).

Hope it helps :octocat:

**Comment by tymondesigns** [comment]
> Are the tokens safe?

You should read up on the pros and cons of json web tokens. Lots of material online going through this stuff. Also note this library currently uses JWS (JSON Web Signature) to encode the tokens via [namshi/jose](https://github.com/namshi/jose).

The token payload is readable by any third party if they get their hands on it. Since base64 is used to encode the claims. The signature that goes along with it, is the thing that will prevent the payload being tampered with, since it uses HMAC.

> As a side request, I would like to know the "flow" of the process and if possible, please add more documentation.

It depends what flow specifically? token creation, authentication, refreshing etc?
And I am working on some new docs to coincide with the `0.6` release

**Comment by elsodev** [comment]
@tymondesigns great work you have done here, i have a question.

As mentioned by @jossemarGT communications channel is always the threat, SSL is the current solution to it, but yet again SSL may fail (it did happen), we still need the data passing around to be secured,

 Is there any way we can encrypt the json JUST in case SSL failed(highly unlikely), json is still unreadable.

Just reaching out for your suggestions.

thanks.

**Comment by kfirba** [comment]
@elsodev just don't include any sensitive data. By default it will include the ID of the user which isn't sensitive at all. 

Even if the SSL fails, the token is only valid for a specified amount of time. You can make the token expire in an hour, or expire it manually at every request and generate a new one for the user. The package comes with a token refresh middleware which will simply generate a new token for each request while invalidating the old one which means that even if your token was exposed, once you make another request the exposed token will be invalidate.

**Comment by tymondesigns** [comment]
@elsodev this library currently uses JWS (JSON Web Signature) to create the tokens, which, as the name suggests, means the tokens are 'signed'.

I think in the major release after `0.6` I will introduce an option to use JWE (JSON Web Encryption) which will indeed encrypt the token

**Comment by tymondesigns** [comment]
Also note that you could implement it yourself by implementing your own version of `Tymon\JWTAuth\Contracts\Providers\JWT` and passing that into the config
