### ISSUE TITLE
Add warning for README.MD or wiki pages that default configuration is not safe for production!

### ISSUE THREAD

**Issue by ghost** [tymondesigns/jwt-auth#1754]
### Subject of the issue
I think you should warn developers that their jwt hashes can be easily cracked with default configuration and their user accounts can be easily compromised! 

### Your environment
| Q                 | A
| ----------------- | ---
| New Feature?      |  yes

### Expected behaviour
Say with big text on the README.MD "DONT RUN JWT-AUTH WITH THE DEFAULT CONFIGURATION ON THE PRODUCTION!!!!!!!!"

**Comment by lukepolo** [comment]
What seems to be wrong with it? The install does say to assign the `JWT_SECRET`, i guess if they don't enter one it could be an issue.

**Comment by ghost** [comment]
jwt-auth uses unsecured HS256 algorithm by default! It must use RS256 which impossible to crack! https://github.com/lmammino/jwt-cracker

**Comment by lukepolo** [comment]
You should make a PR to change the default. But really it says with weak secrets 

`Effective only to crack JWT tokens with weak secrets`

**Comment by tymondesigns** [comment]
@marataziat The minimum recommended key length for HS256 (HMAC + sha256) is 32 bytes or 256 bits. Since one character is 1 byte, the secret key that is generated by default is sufficient at 32 characters long.

Ultimately we will all be long dead before any successful brute forcing could occur 

Here are some links on the subject
https://security.stackexchange.com/questions/95972/what-are-requirements-for-hmac-secret-key
https://crypto.stackexchange.com/questions/34864/key-size-for-hmac-sha256

Having said that however I have just bumped the default key length to 64 characters (512 bits) to put that to bed.

Thank you for raising the issue though, and I think it probably does warrant a warning in the documentation, that weak/low length keys are susceptible to brute forcing
