### ISSUE TITLE
Subject lock not works

### ISSUE THREAD

**Issue by zakulqi** [tymondesigns/jwt-auth#1769]
### When using \Tymon\JWTAuth\Http\Middleware\Authenticate middleware, it not checking prv parameter, to verify model.

| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel 
| Framework version | 5.8.2
| Package version   | 8dfa7952bf752ea1867fcb038a92e01e4b0d8668
| PHP version       | 7.3.2

### Steps to reproduce
Create two guards with jwt driver. Enable lock_subject if not. Get token for first guard, and try to auth with this token on second guard.
Middleware used for route to auth with token: \Tymon\JWTAuth\Http\Middleware\Authenticate

### Expected behaviour
Must throw exception, because token not valid for other model.

### Actual behaviour
Passes condition.

I'm finded the problem in \Tymon\JWTAuth\JWTAuth:L66 `if (! $this->auth->byId($id)) {`
It try's to find user by id, and saves this user to guard.
On L71, it returns user `return $this->user();`
But In JWTGuard:L74, it check if it not null. And it always not null, because it previously set. And subject not validates.
![image](https://user-images.githubusercontent.com/38406949/53699506-fea6b500-3df9-11e9-9174-0cdb6d2726dc.png)

**Comment by tymondesigns** [comment]
I will put this at the top of my list of things to look into :+1:

**Comment by linkjian** [comment]
@tymondesigns Hi, I also encountered this problem, but I need to use multiple users. After I try to delete the code of JWTGuard:L74-L76, multi-user can work. Can I temporarily delete this code to use? like this:
![Screenshot from 2019-03-20 01-02-16](https://user-images.githubusercontent.com/48601161/54626365-fc0bb700-4aab-11e9-863a-963989014205.png)

**Comment by zakulqi** [comment]
> 
> 
> @tymondesigns Hi, I also encountered this problem, but I need to use multiple users. After I try to delete the code of JWTGuard:L74-L76, multi-user can work. Can I temporarily delete this code to use? like this:
> ![Screenshot from 2019-03-20 01-02-16](https://user-images.githubusercontent.com/48601161/54626365-fc0bb700-4aab-11e9-863a-963989014205.png)

It solves my problem
https://gist.github.com/zakulqi/5f3e34638c169114a75de704df4b7d2c

**Comment by kilvn** [comment]
我也遇到了这个问题，不得不说JWT-Auth是真的坑，差评。

**Comment by prookie** [comment]
Hi!

This still seems to be bugged in the current version, which is a security dealbreaker if there are two distinct login areas for standard user accounts and admins for example like in my current project.

Any chance to get it fixed?

**Comment by prookie** [comment]
FYI, my workaround at the moment is to fix the existing user assignment which does not validate the token subject beforehand. I extended the implementation of `\Tymon\JWTAuth\JWTGuard` and added the validation to the `onceUsingId()` method (like in the getter `user()`):

```
    public function onceUsingId($id)
    {
        if ($this->jwt->setRequest($this->request)->getToken() &&
            ($payload = $this->jwt->check(true)) &&
            $this->validateSubject()
        ) {
            return parent::onceUsingId($id);
        }

        return false;
    }
```

This class is registered as an additional auth guard driver and then used instead of `jwt`.

I am not entirely sure if that is the only place where the unvalidated assignment happens, so... bad feeling while handling authentication in an application.

**Comment by Dexalt142** [comment]
> @tymondesigns Hi, I also encountered this problem, but I need to use multiple users. After I try to delete the code of JWTGuard:L74-L76, multi-user can work. Can I temporarily delete this code to use? like this:
> ![Screenshot from 2019-03-20 01-02-16](https://user-images.githubusercontent.com/48601161/54626365-fc0bb700-4aab-11e9-863a-963989014205.png)

This solution actually works. Thank you.

**Comment by tymondesigns** [comment]
The issue here is that you are using the package Authenticate middleware, alongside using laravel guards. The Authenticate middleware that comes with this package was created before laravel had any concept of auth guards, and was kept for backwards compatibility with the `JWTAuth` facade.

If you are utilising laravel guards, you should use the laravel built in middleware which accepts a guard parameter e.g. `->middleware('auth:api')`

I understand that this is not abundantly clear so I will update the documentation with this gotcha

Thank you for your patience
