### ISSUE TITLE
authenticated user attributes are all string

### ISSUE THREAD

**Issue by kfirba** [tymondesigns/jwt-auth#190]
Hello.

When I use the `jwt.auth` middleware and later then in my application I try to get the user from the request object the attributes are ALL casted to string. The ID which suppose to be an integer is now a string, any boolean field is "1" or "0" which really sucks. Why is that happening?

**Comment by tymondesigns** [comment]
This is because the default behaviour of `json_encode` will cast all values to a string. 

This is done in the underlying library [here](https://github.com/namshi/jose/blob/master/src/Namshi/JOSE/JWT.php#L59)

**Comment by kfirba** [comment]
@tymondesigns Then why not use a regex to deal with it? I know that there is an option you can pass to the `json_encode` function to `JSON_NUMERIC_CHECK `  but it might be dangerous as there were reports of string like `'+33123456789'` casted to `33123456789`. 

There is a suggestion in SO to do something like: 

```php
$json = preg_replace('#:"(\d+)"#', ':$1', $json);
```

which will simply convert and "{NUMBER}" to {NUMBER}.

**Comment by tymondesigns** [comment]
Yep, that's what i'd do if I had control over it. 

The point is that I don't. Since it's the 3rd party [namshi/jose](https://github.com/namshi/jose) library that this package uses to do the heavy lifting of encoding and decoding the tokens, and no matter how I pass the payload to it, it will always call `json_encode` in it's standard form, resulting in everything being cast to strings.

Is there a reason you can't transform this on the client? what frameworks (if any) do you use on the client?

**Comment by kfirba** [comment]
@tymondesigns Well I can do that. I just thought it would be better if you could add it, one less thing to worry about. I just had some "gotcha" moments where I wrote some tests and my tests failed and I didn't understand what was going on cause I was anticipating an integer and my tests asserted against an integer and then I realised that the package returns a string :)

Well you may want to mention it for future reference somewhere.

**Comment by tymondesigns** [comment]
No worries, it's not ideal I know.. Maybe it would be worth a PR on namshi/jose

Cheers
