### ISSUE TITLE
Jwtauth::attempt not woking with my posgresql

### ISSUE THREAD

**Issue by ducnvhn** [tymondesigns/jwt-auth#197]
I have a very strange problem cannot figure it out. 

I try to authenticate user using JWTAuth::attempt($credentials) using user email and password. Everything work fine with MySQL but when I switch the my database to Postgresql it cannot work anymore.The error is always "invalid credentials". Anyone can point me out pls.

**Comment by tymondesigns** [comment]
Not used postgres myself. But it shouldn't make a difference, given that Laravel's Auth already abstracts this away. I will check it out when I can

**Comment by ducnvhn** [comment]
thank you for your response. 

I'm now looking at the Collation and Character type settings on both DB but couldn't figure it out yet.

**Comment by Gummibeer** [comment]
We got another problem with the attempt() function. We also use email & password but the attempt always give ```false``` - we created our own Model, called Account, but changed it everywhere (auth & jwt config). If we get the Model the "normal" way, chach the password with the Hash class and than generate the token from User-Model it works. A very strange bug - and no idea where the problem is.

**Comment by SeBuDesign** [comment]
@Gummibeer I have the same issue have you found a fix for it? Thanks!
