### ISSUE TITLE
Refreshed token `exp` can be older than `iat` + refresh_ttl - that would force the user to login again in some cases

### ISSUE THREAD

**Issue by dani3l** [tymondesigns/jwt-auth#201]
Hi 
I noticed that `exp` timestamp can be older than `iat` + refresh_ttl
Let's say the user haven't logged in two weeks-1min and tries to refresh the token
token is being refreshed, but the next time he tries to refresh it, it would throw a TokenInvalid since the `iat` timestamp is not renewed.

Is there something I'm missing or should I implement this use case myself?  (check for iat + refresh_ttl and generate an entirely new token if needed)
thanks!

**Comment by tdhsmith** [comment]
Isn't this the intended functionality? We set the window of time (`refresh_ttl`) from an initial login (`iat`) that a user can refresh *within*, not the time from the last refresh. Otherwise the user could chain refreshes forever and never revalidate their credentials.

Maybe there is a use-case for this but I prefer the current form, because otherwise I would have to manually force a user to log out periodically (or risk exposing a huge attack surface; an attacker merely has to refresh every once in a while and they have a perma-token).

**Comment by tdhsmith** [comment]
![image](https://cloud.githubusercontent.com/assets/1791252/9459832/860d7370-4ac5-11e5-9b01-d4f78751209f.png)

**Comment by tymondesigns** [comment]
I still might pinch this illustration :smile:

**Comment by tdhsmith** [comment]
No problemo! I was crafting it for the docs, but obviously that got lost on the sidelines. (the code is in [this gist](https://gist.github.com/tdhsmith/9c64d84fd77801dc782f))
