### ISSUE TITLE
Important Questions

### ISSUE THREAD

**Issue by juankprz** [tymondesigns/jwt-auth#2045]
can jwt-auth coexist with other packages such as laravel passport and jetstream? 

| Framework         | Laravel

**Comment by miguel456** [comment]
I don't see why it wouldn't "coexist" with other packages. 

Jetstream already has authentication implemented so you'd have to make changes if you really wanted to use JWT, and Laravel Passport uses Oauth which is an entirely different concept than JWT. You could definitely use them together.

Packages don't really conflict with each other until you start using them in the code. This package might conflict with other JWT packages because they do similar things, but only if you use them at the same time, which is kinda illogical. Hope this answered your questions.

**Comment by juankprz** [comment]
Thanks
