### ISSUE TITLE
Bug: JWTAuth->setToken() nests tokens

### ISSUE THREAD

**Issue by swayok** [tymondesigns/jwt-auth#211]
Version: 0.5.4

How to test:
`$token = \JWTAuth::parseToken(); // $token->token->value is string`
`$token->authenticate() // $token->token->value is Token Object`

Reason:
in `JWTAuth->requireToken()`
JWTAuth line 285: `$token = $token ?: $this->token`
then on JWTAuth line 289: `$this->setToken($token);` where `$token` is already a `Token` object

Fix:
JWTAuth line 269 (setToken method): 
`$this->token = $token instanceof Token ? $token : new Token($token);`

**Comment by tdhsmith** [comment]
I think this is already fixed on the develop branch, see [`JWTAuth->requireToken()`](https://github.com/tymondesigns/jwt-auth/blob/3799b2ac1da279606a0fab668fae77fffb67b747/src/JWTAuth.php#L270). The function no longer even bothers trying to set the token, which I think is a good separation of concerns. (though your solution would've worked as well)

Also note that `parseToken()` is just returning the `JWTAuth` class, so labelling it as `$token` is a little confusing. And since you're using the facade, you don't even need that variable.
```php
JWTAuth::parseToken();
JWTAuth::authenticate();
```

**Comment by tymondesigns** [comment]
@tdhsmith is correct... I'm hoping things are a little simpler and clearer in the new version
