### ISSUE TITLE
Invoking jwt:generate doesn't refresh the secret

### ISSUE THREAD

**Issue by mtpultz** [tymondesigns/jwt-auth#216]
I pulled in JWT-Auth and ran the install, but when I tried to regenerate the token it always remains the same in config/jwt.php, and if I included JWT_SECRET within .env where I would have expected the token to be set it doesn't get rewritten there either.  Is there a way to reset the token from the command line, I've set it up in my .env and just copied the new secret there from the command line, maybe that was the intent.

**Comment by tdhsmith** [comment]
Based on previous discussion at #138:

The default functionality is to change the value present in `config/jwt.php`, but only when the key there matches what key `artisan` sees. If you're using env files, then the current intent is that you use the show command `php artisan jwt:generate --show` and copy-paste the value, like you said. 

If you have an environment file, the config file won't get updated, because it uses a [simple string replace to swap the current key value with a new one](https://github.com/tymondesigns/jwt-auth/blob/develop/src/Commands/JWTGenerateCommand.php#L51). If your env file has a *different* key, that will be the key the Laravel application has in memory, so it won't match the config one and nothing will be replaced.

I have no idea if the author would be interested in expanding the command's functionality to include env files or not, he didn't say last time. Just thought I'd share this info.

**Comment by tymondesigns** [comment]
No plans to change this at the minute.

@tdhsmith thanks for helping out on these issues :+1:

**Comment by Donatello-za** [comment]
Wouldn't it be better to keep things standard, i.e. the same way that Laravel writes to the .env file when running `php artisan key:generate`?

**Comment by tymondesigns** [comment]
@Donatello-za it is effectively the same now as mentioned in https://github.com/tymondesigns/jwt-auth/issues/138#issuecomment-159979197.

There are some slight differences, but that's because laravel's command can safely assume that a `APP_KEY` will already be present in the `.env` file. SO some some extra checks are needed for this package

**Comment by Donatello-za** [comment]
Thanks, I missed the fact that you actually did work on this, as mentioned in my other comment, it is much appreciated!

**Comment by tymondesigns** [comment]
No worries :smile:
