### ISSUE TITLE
Remember Me with token

### ISSUE THREAD

**Issue by lucianovns** [tymondesigns/jwt-auth#222]
Hi, is there a way to keep "logged in" the user ? like a remember me function 

I need to generate a unique token that is going to be associated to a device_uuid and a device_os . This will keep me logged in permanently, and on each request i will send the token and the uuid if it matches with the token and uuid associated for the user it will allowme to interact with the others api services. 
Can i achieve that with this package? maybe using Creating a Token based on anything you like and create the token with device_uuid device_os and user info. But what about the remember me function? can i set a token with no expiration?  Thanks in advance

**Comment by npx** [comment]
I think you have misunderstood how JWTs work in general.

The beauty of the JWTs is that you do not store them in a database.

The token is created on the server (by using a secret only the server knows) and a user by some means needs to authenticate to get their hands on that token. The token only exists for the time the user is holding onto it (and until it is not valid anymore).

In your case, the device_uuid and device_os is what would identify the client.
This goes into the payload of your token, along with how long the token is valid and how long it can be refreshed.

Your user/client saves this token, which in your case either needs a super high expiration time (to expire never) or a huge refresh time (a bad idea because in case someone finds an expired token somehow and sends it to your server, it will be refreshed and the malicious user now has a valid token).

So as long as the user/client saves this token with a high (almost infinite) expiration time in one way or another (local storage comes to mind) the user can be authenticated without acquiring another token (by the means of logging in for example).

However, a high expiration time is not encouraged, unless you also implement a blacklist system that can store tokens that are illegal. This is in case a third person gets the hold of the token (which should never happen anyway but not using https in the right places or other failures in handling secret information, always results in a leak of sensitive data) you need to make sure that this token cannot be used anymore.

I hope I understood your question and this is somewhat helpful to you.

**Comment by tymondesigns** [comment]
As @npx has mentioned, "remember me" functionality is intrinsically at odds with stateless authentication. But that's not to stop you implementing your own business logic around this package, as long as you are aware of the drawbacks and security implications of said implementation.

The upcoming release will have support for non expiring tokens, and the ability to blacklist them indefinitely, so that should hopefully help :)
