### ISSUE TITLE
Custom token claim with additional payload

### ISSUE THREAD

**Issue by kennyyap92** [tymondesigns/jwt-auth#226]
Hello tymon, would like to apologies at first because i am not very familiar with jwt but I have managed to solve my previous invalid algo problem, but i face another problem whereby i understand that in the jwt config file i can manually specify the user identifier, which is all fine and i can manage to create a token and get the user by using JWTAuth::toUser($token). What I would like to ask is that because all communication in my website uses a UUID which I would like to add into the token claim as a payload so when the token is being sent to the mobile app, they can decode the token and get the UUID for any further request. I wonder if there is such a way to append additional things into the token and then decode it in javascript to get the claims?

Thanks in advance.

**Comment by tdhsmith** [comment]
You can attach the UUID as a custom claim before the token is generated. Assuming you're using `fromUser`...

For **≤ 0.5.4**:
```php
JWTAuth::fromUser($user, ['uuid' => $uuid]);
```
For **develop**:
```php
JWTAuth::customClaims(['uuid'=>$uuid])->fromUser($user);
```

If you're using the factory directly, similar methods exist (eg `$payloadFactory->addClaim('uuid',$uuid);`).

Once the token is received and decoded by your javascript JWT library, you'll find the UUID in the resulting JSON payload under the 'uuid' key, alongside all the standard claims.

**Comment by kennyyap92** [comment]
@tdhsmith Thank you so much. This is what I really needed. One more question, can i check with you, if I understand the module correctly, whenever the server receive a request that has to be processed and authenticated by the jwt module, it uses the 'sub' field of the token which is technically the user_id and then using the default laravel authentication to authenticate a user by their user_id right?

So i would like to check, in my case I have a user_id and a UUID but my authentication will be using UUID to determine if the user exist. Such design is due to the fact that the initial user_id which is also the primary key of the table, should not be changed because it is use to connect all the rest of the tables. So we introduced the UUID column which serves to replace the user_id for all requests and actions such that if one person's UUID is compromised, the person can just reset another UUID instead of their user_id.

So in this case, how should I tell this jwt module to authenticate the user instead of ```$this->auth->byId($id)``` is there a way i can do like ```$this->auth->byUUID($uuid)``` ?

**Comment by tdhsmith** [comment]
Yes you are correct!  And it sounds like you should really be using the UUID as your subject claim and not include the primary key anywhere, if you want to keep the id secure. By setting `identifier` (and potentially `user`) in the JWT configuration, you can change what field and model the helper methods use in subject claims.

Once you change that, `toUser`, `fromUser`, and `attempt` should all work normally. `authenticate` will not work because it uses `byId`. You can fix this by editing the auth provider, but it's a lot easier to use `toUser` instead, because they do pretty much the exact same thing.

Here's a longer breakdown I wrote earlier:

### Creating Tokens
##### `JWTAuth::fromUser($user)`
This function sets the subject to `$user->{$identifier}`(see [JWTAuth.php#L84](https://github.com/tymondesigns/jwt-auth/blob/0.5.4/src/JWTAuth.php#L84)), so once you change the configs, it should work.  However if you use this method, you will need to verify their credentials manually.

##### `JWTAuth::attempt($credentials)`
Here you can switch to using the UUID in your credential array (assuming it is stored on your User model):
```php
JWTAuth::attempt(['uuid' => $uuid, 'password' => $password]);
```
That will work fine because [the default Eloquent provide for Auth\Guard](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Auth/EloquentUserProvider.php#L87) generates something like `User->where('uuid','=',$uuid)->first();` and that isn't dependent on having the primary key. Then afterward the function uses `fromUser`, so your `identifier` setting will come into play, like above.

### Authenticating Tokens
##### `JWTAuth::toUser(JWTAuth::getToken())`
This will also utilize `identifier`, so if you set the configs correctly, everything will work out fine.

##### `JWTAuth::parseToken()->authenticate()`
This is where your `this->auth->byId($id)` line comes from. You *could* implement your own `AuthInterface` or extend [`IlluminateAuthAdapter`](https://github.com/tymondesigns/jwt-auth/blob/0.5.4/src/Providers/Auth/IlluminateAuthAdapter.php) with custom `byId($id)` behavior (and then set it in config under `providers.auth`). But the function really does the exact same thing as the previous one: it retrieves the subject claim from the token and then tries to find a matching User. **I think it's a lot easer to just use `toUser` and ignore `authenticate`.**

**Comment by kennyyap92** [comment]
Alright @tdhsmith I will try to implement it and then update you the results...

**Comment by tdhsmith** [comment]
You should be able to override the default by passing it in as a custom claim, just like I did in with the `uuid` claim in the first response.
```php
JWTAuth::fromUser($user, ['iss'=>'*.example.com']);
// (or)
JWTAuth::attempt($credentials, ['iss'=>'*.example.com']);
```
I don't think JWTAuth uses that claim for anything, so you should be able to set it to whatever you like without repercussions on this side. ([The spec](https://self-issued.info/docs/draft-ietf-oauth-json-web-token.html#rfc.section.4.1.1) says the usage of `iss` is 'application-specific'.)

**Comment by kennyyap92** [comment]
@tdhsmith  sorry for the late reply, it takes me some time to figure out how the workflow is but i somehow came up with this. The code is pretty much a modification of the base middleware but i've added support to send the user their new refreshed tokens via response headers so they can catch it in the client side application. I am not very sure if this is the best approach and if it has any security issues that i could not identify. Please do enlighten me if you've found something i dont. 

    namespace Core\JWTAuth\Middleware;

    use Core\JWTAuth\Exceptions\JWTException;
    use Core\JWTAuth\Exceptions\TokenExpiredException;

    class ExtendedGetUserFromToken extends BaseMiddleware
    {
        public function handle($request, \Closure $next)
        {
            $newToken = null;

            if (! $token = $this->auth->setRequest($request)->getToken()) {
                return $this->respond('jwt.absent', 'token_not_provided', 400);
            }

            try {
                // Ingore default auth, get user by UUID
                $user = $this->auth->toUser($token);

            } catch (TokenExpiredException $e) {
                // Generate new token and attempt authentication
                $newToken = $this->auth->refresh($token);
                $user = $this->auth->toUser($newToken);
            
            //return $this->respond('jwt.expired', 'token_ttl_expired', $e->getStatusCode(), [$e]);

            } catch (JWTException $e) {
                return $this->respond('jwt.invalid', 'token_invalid', $e->getStatusCode(), [$e]);
            }

            //If no such user
            if (! $user) {
                return $this->respond('jwt.user_not_found', 'Invalid UUID', 404);
            }

            $this->events->fire('jwt.valid', $user);

            //Transform response
            $response = $next($request);

            // If new token exist, send back to user via response header
            if($newToken != null){
                $response = $response->header('New-Jwt-Token', $newToken);
            }
             return $response;
        }
    }
