### ISSUE TITLE
Getting decoded claims in the application

### ISSUE THREAD

**Issue by yisyang** [tymondesigns/jwt-auth#241]
##### Sorry if this question is actually trivial, but I'm not able to find instructions on how to actually use the (custom) claims added into the token.

So far I'm using
```
\JWTAuth::decode(\JWTAuth::getToken())->toArray();
```
But I'm sure there must be a better way.

---

##### More details on what I have at the moment (using Lumen):

* app/Http/routes.php
```
$app->group(['prefix' => 'test', 'namespace' => 'App\Http\Controllers\Test', 'middleware' => 'jwt.auth'], function ($app) {
    $app->get('/test-database', 'TestController@testDatabase');
});
```

* app/Http/Controllers/Test/TestController.php
```
class TestController extends Controller
{
	public function testDatabase() {
		$userInfo = \JWTAuth::decode(\JWTAuth::getToken())->toArray();
		$results = CookieMonsterOnAHorseModel::find($userInfo['cookie_monster_on_a_horse']['id'])->horse;

		return $results;
	}
}
```

**Comment by tdhsmith** [comment]
Instead of `\JWTAuth::decode(\JWTAuth::getToken())`, you can just call `JWTAuth::getPayload()`. You don't have to pass it a token, because the JWTAuth class has a local copy that the middleware parsed from the request.

If you're only using one or two custom claims, it's probably simpler to get them with `$payload->get('claim_name')`. This method uses Laravel's [`array_get()`](http://laravel.com/docs/5.0/helpers#arrays) helper so you can even use dot notation to access deep elements.

Together you'd have something like:

```php
    public function testDatabase() {
        $cookieMonsterOnAHorseID = \JWTAuth::getPayload()->get('cookie_monster_on_a_horse.id');
        $results = CookieMonsterOnAHorseModel::find($cookieMonsterOnAHorseID)->horse;

        return $results;
    }
```

**Comment by yisyang** [comment]
Thank you so much for the quick and detailed response!

Would you happen to have access to the wiki? I think others may find this helpful too.

**Comment by tymondesigns** [comment]
i'll make sure this stuff is covered :+1:
