### ISSUE TITLE
JWT Configuration breaks config caching

### ISSUE THREAD

**Issue by LiamHaworth** [tymondesigns/jwt-auth#254]
The laravel app I am currently developing makes use of route and config caching to boost performance but we started running into problems once I introduced the `jwt-auth` dependence.

I have run the command suggested in the wiki to produce the JWT config file and that work all fine and dandy. But once it is deployed to the server and the config cache is generated it bails with the following error

```
PHP Fatal error:  Call to undefined method Closure::__set_state() in /var/www/********/bootstrap/cache/config.php on line 196
``` 

If I disable the config caching it works fine and if I removed the dependence and its config then generate a cache it also works fine.

From what I can tell it is the following two parts of the JWT config that are tripping up the cache generator

```
       'auth' => function ($app) {
            return new Tymon\JWTAuth\Providers\Auth\IlluminateAuthAdapter($app['auth']);
        },

        'storage' => function ($app) {
            return new Tymon\JWTAuth\Providers\Storage\IlluminateCacheAdapter($app['cache']);
        }
```

**Comment by tdhsmith** [comment]
You should be able to replace the closures with string or `::class` format names. Copy [the config file on the develop branch](https://github.com/tymondesigns/jwt-auth/blob/develop/config/config.php#L106), but substitute class names as necessary (`...\Auth\Illuminate` and `...\Storage\Illuminate` on the develop branch are called  `...\Auth\IlluminateAuthAdapter` `...\Cache\IlluminateCacheAdapter` in 0.5.x).

I _think_ the closures were necessary at one point because Laravel wouldn't automatically inject Auth and Cache properly? But I don't believe that's a problem anymore.
