### ISSUE TITLE
ParseUser Adapter for this repository

### ISSUE THREAD

**Issue by gweiss27** [tymondesigns/jwt-auth#263]
I use your repository with the Parse.com platform and right now it does not support ParseUser tokens.  I have created a very simple ParseUserAdapter that works with the Parse API to allow creating tokens.  I am submitting this issue and would like to submit my provider to add to the overall project.

Thanks,

Greg

**Comment by tdhsmith** [comment]
Are ParseUser tokens JWTs? As far as I can tell from the documentation, they are arbitrary strings without any decodeable information... please correct me if I'm wrong!

JWT, despite its vague name, is [a very specific, well-defined format](https://tools.ietf.org/html/rfc7519) that allows transmission of small amounts of data ('claims') within the token string.

(But even if the code isn't appropriate for this library, do consider putting it online, because that doesn't mean it isn't useful to others! :smiley:)

**Comment by tymondesigns** [comment]
I think Parse.com token are a different thing, correct me if I'm wrong?

**Comment by gweiss27** [comment]
I'm using your package with Parse for application validation.  Parse.com tokens are different, but you can still validate a user with credentials and then generate a Laravel JWT that works across the app (ie: Angular on the front-end and Laravel for an API.  

In this case, I needed to create my own ParseUserAdapter to validate my Parse.com user object.  So I just created a very simple one using your template and it works.  The problem is, since this file is not part of your package, everytime I deploy I have to keep manually adding my custom adapter to the files on my server which is a pain.

NOTE:  I noticed you moved away from this with the new dev build and I have already modified my application to use the dev-develop branch of your package.  I implemented the JWTSubject interface on my user object and it works great.  So it would awesome if you could add my file to the current production package of jwt-auth, but at this point thats completely up to you.  Maybe someone else trying to use Parse can benefit from it.  If you look at the file it is EXTREMELY simple, so it wont mess up anything, and I did send you instructions on how I use it (I believe).  I can resent those if needed.

Thanks for such amazing work to-date!  I live for this package! :)
