### ISSUE TITLE
refresh, blacklist, logout

### ISSUE THREAD

**Issue by francoismart** [tymondesigns/jwt-auth#276]
Hello

From a mobile app as client, I use a laravel api as server with 1 route group having [jwt.auth, jwt.refresh]. it works.

To be able to login, I've put the /login, /logout and /refresh outside the group. 

If it's non standard and I need a better way please let me know. 

My question then is this 

If I put  JWTAuth::invalidate(JWTAuth::getToken()); inside my logout, then the token is blacklisted.ok.

But is there a list of invalidated (blacklisted) tokens somewhere ? 

Or maybe the real question, how do I ensure that when user is "unlogged" so that no more tokens are valid for this user: do I need a Boolean column in my user table saying logged or not logged ?  

In fact what is a blacklisted token please ?

Point is, if i do logout, wait until ttl expire of precedent token and to "refresh" with it, it refreshes and  then I can reenter API with refreshed token ...

What I say in other words is : how could the refresh route know that the user is logged out and return a 401 ?

Have a nice day
Francois

**Comment by tdhsmith** [comment]
> But is there a list of invalidated (blacklisted) tokens somewhere ?

> In fact what is a blacklisted token please ?

Yes, it is stored in your cache. A blacklisted token is simply a token whose `jti` claim is listed in the cache. The location/type of your cache depends on Laravel's configured _cache driver_ (usually `file` by default).

> Or maybe the real question, how do I ensure that when user is "unlogged" so that no more tokens are valid for this user: do I need a Boolean column in my user table saying logged or not logged ?

> What I say in other words is : how could the refresh route know that the user is logged out and return a 401 ?

You probably have 2 main options here:

1. Like you said, when the user logs out, set a `logged_out` flag in the DB. However this requires you to either:
 - Check for that flag on _every request_, which isn't ideal because you are basically re-implementing a session system on the back end, which somewhat "defeats" the purpose of tokens. (Why not just use Sessions?)
 - Check for that flag _only when the user tries to refresh a token_, which means tokens will stay valid for a bit after a user logs out, but won't be able to be refreshed. For some applications, this may be sufficient (and your users won't know the difference because the client can just forget the token existed), but if you absolutely need tokens invalidated immediately on log-out, it won't work for you.

2. Keep a list of each user's `last_active_token` in the DB (update this whenever you issue or refresh a token). Then on logout/password change, invalidate that token. Fundamentally this isn't that much different from (1), **but** it allows the work to be done by the built-in Blacklist.
