### ISSUE TITLE
Get payload without signature?

### ISSUE THREAD

**Issue by Fossil01** [tymondesigns/jwt-auth#280]
It should be possible to look inside the token to get the payload without having the signature. Just like JWT.io does.

How is this done with jwt-auth because it keeps complaining it could not verify the signature when trying to decode it but it doesn't even need one.

**Comment by npx** [comment]
If you want to look inside the payload, you can easily decrypt it with base64.

But why would you want to look into the payload of a token of which the signature cannot be verified?

If you are going to do any sensitive operation based on the payload that was not signed properly, I can send you a bunch of tokens and use your app without ever the need to get a valid token from your server.

**Comment by tymondesigns** [comment]
not something I think needs to be implemented

**Comment by antonioreyna** [comment]
I find it useful because for example now i need to send an appkey in the token that appkey is a hash that then i look into the database to get a real signature this is to allow my jwt login accept different apps linked to my api each app with its own secret.  

I was able to sign the jwt with a different secret.
