### ISSUE TITLE
Custom User model extending NeoEloquent failing.

### ISSUE THREAD

**Issue by agoransson** [tymondesigns/jwt-auth#295]
I get the following error trying to use this package. I've followed the instructions, and I use a standard config (the only change is the model namespace).

The custom model extends [NeoEloquent](https://github.com/Vinelab/NeoEloquent)s model, not standard Eloquent model. I've tried with both "clean" model without the auth traits, and following the standard Laravel model (with the auth traits). Both generate the following error, so I'm left to believe it's not a problem with the model, but with the configuration.

    ErrorException in Builder.php line 217:
    Argument 3 passed to Illuminate\Database\Query\Builder::__construct() must be an instance of Illuminate\Database\Query\Processors\Processor, null given, called in /home/vagrant/projects/goodtrade/api-app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1918 and defined

This is my jwt.php config, as you can see I've only changed the user model - which actually is an Eloquent model so I expect the providers should not have to be changed.

```php
<?php

return [

    'secret' => env('JWT_SECRET', 'lKditbDBMDARG0A859js55yAEfKJ0iKP'),

    'ttl' => 60,

    'refresh_ttl' => 20160,

    'algo' => 'HS256',
		
    'user' => 'My\Custom\Model\User',

    'identifier' => 'uuid',

    'required_claims' => ['iss', 'iat', 'exp', 'nbf', 'sub', 'jti'],

    'blacklist_enabled' => env('JWT_BLACKLIST_ENABLED', true),

    'providers' => [

        'user' => 'Tymon\JWTAuth\Providers\User\EloquentUserAdapter',

        'jwt' => 'Tymon\JWTAuth\Providers\JWT\NamshiAdapter',

        'auth' => function ($app) {
            return new Tymon\JWTAuth\Providers\Auth\IlluminateAuthAdapter($app['auth']);
        },

        'storage' => function ($app) {
            return new Tymon\JWTAuth\Providers\Storage\IlluminateCacheAdapter($app['cache']);
        }

    ]

];
```

Any idea what, or where, things are failing?

**Comment by tdhsmith** [comment]
What are you calling when it fails?

Have you set `'model'` in `config/auth.php` to your new model? JWTAuth relies on Laravel's `Auth` for some functions.

Can you successfully call `Auth` functions? Like `Auth::loginUsingId($id);` or `Auth::attempt($credentialArray);`?

If there's something breaking in the Auth/User interfaces, you could fix it with a custom provider. But first we need to know _what_ is breaking. (Also there shouldn't be a problem since everything just extends Eloquent models).

**Comment by tdhsmith** [comment]
I just noticed you're using `uuid` as your identifier. I'm not very knowledgeable at changing that sort of thing, but there could definitely be some hiccups there, because that detail has to get passed to a lot of different classes. Is `uuid` your primary key? If not, you might have to do override `getAuthIdentifier()` or something like that... And if so, are you setting `$primaryKey` in your user model?

Just bumbling / thinking aloud.

**Comment by agoransson** [comment]
I tried now with a fresh install of Laravel 5.1.19 (some breaking changes in 5.1.20 for NeoEloquent) and NeoEloquent 1.2, and jwt-auth 0.5.5 and I do **not** get the same builder exception - which is odd. It might be that some other package is messing the installation up.

The UUID, as you pointed out, does cause an issue unless the authentication mechanism in laravel knows that it should change the primary key (as far as I understand Neo4j the node ID property is reusable and should not be used as unique identifier, that's why I always use UUID when working with neo). I just overwrote the primary key in the model to fix that.

```php
$primaryKey = 'uuid';
```

It seems to generate a proper JWT in my fresh install, although [jwt.io](http://jwt.io/) claims it's an invalid token. Perhaps I'm missing another setting.

Here's the generated token.

```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4YTJiYjNlOC03NjgyLTExZTUtYjAyNi02MDAzMDg5ZDQ0ZmEiLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXV0aCIsImlhdCI6IjE0NDUyNzM4ODkiLCJleHAiOiIxNDQ1Mjc3NDg5IiwibmJmIjoiMTQ0NTI3Mzg4OSIsImp0aSI6IjFjZWMwNGFiYzAxMjM3YzY5MmI4ZmQ2YzQzYjc4ZDAxIn0.c5PxMTuCNqjbC-g4JIVyVRg43-rze7fYjmf0g1_-jLk
```

**Comment by tdhsmith** [comment]
Well I'm glad it seems to be working, though it's always a little frustrating if you don't figure out what had been wrong!

Not sure if you figured out the jwt.io issue or just took the key out of your post for security reasons, but note that the form on that site has a tiny box to paste your secret key into on the bottom right. (No one ever sees it.) If you don't do that, it'll always tell you "Invalid Signature", but as long as you see claims being decoded, then everything else is fine.

And you probably already did this, but be sure to regenerate your secret key since posting it in the original issue. ;)

**Comment by agoransson** [comment]
I just noticed the "hidden" box for the secret =) No security issues.
