### ISSUE TITLE
Get CustomClaims from payload

### ISSUE THREAD

**Issue by Krlinhos** [tymondesigns/jwt-auth#297]
Hello, 

I had created a custom payload:

```
$payload = JWTFactory::make(['rol' => 'player']);
$token = JWTAuth::encode($payload);
```
But before when I try to get rol not show 'player', it shows a complete payload object... 
```
$payload = JWTFactory::getPayload($request->input('token'));
$rol = $payload->get('rol');
        
return var_dump($rol);
```

How can I retrive the custom claims?

**Comment by tdhsmith** [comment]
The method you're looking for is on `JWTAuth`, not `JWTFactory`:

```php
$payload = JWTAuth::getPayload($request->input('token'));
$rol = $payload->get('rol');
```

The factory doesn't have that method signature, so you trip [the magic method that adds custom claims](https://github.com/tymondesigns/jwt-auth/blob/0.5.5/src/PayloadFactory.php#L232). `$rol` is just going to be an instance of `PayloadFactory` with the extra claims `'getPayload' => $token` and `'get' => 'rol'`. 

Yeahhh magic methods can be annoying to debug. :weary:

**Comment by tdhsmith** [comment]
Also BTW, `JWTAuth::parseToken()` will save a copy of the token in the class, and it _does_ look at the `token` input param by default. Then it would work to call `JWTAuth::getPayload()` and other methods without a token argument.

Plus, **GetUserFromToken** and [the upcoming **Check**](https://github.com/tymondesigns/jwt-auth/blob/develop/src/Middleware/Check.php) already call the parsing function, so if you're behind one of those middlewares, you don't even have to do that bit yourself.

Just sharing because it's 1) a little simpler, and 2) will be the required usage from 0.6.x onward.

**Comment by Krlinhos** [comment]
Okk! Thanks! Yes, I use middleware GetUserFromToken for some functions. Other functions can be accessed by anyone. But should send a token that was previously generated and must have a specific role. These users do not have to be registered.

Once more time, Thanks! :)
