### ISSUE TITLE
Consider changing to - lcobucci/jwt - JWT library

### ISSUE THREAD

**Issue by vukasin0** [tymondesigns/jwt-auth#303]
I've just check and you are using **namshi/jose** JWT backend.

If you check http://jwt.io/#libraries **namshi/jose** lib isn't up to 100% of spec but it is **lcobucci/jwt**.

**Comment by tdhsmith** [comment]
Interesting. Do you know what the failing claim checks (`sub`, `aud`, `jti`) are? I don't see an explanation anywhere. Is it something about necessary constraints or validation on their values?

**Comment by tymondesigns** [comment]
`namshi/jose` is fully spec compliant.

jwt.io is referring to the validation of those claims (`sub`, `aud`, `jti`) not being part of the package. 

Which is ok, since they are optional claims, and the validation of the claim values is offloaded to this package.

I would accept a PR to add `lcobucci/jwt` support though!

**Comment by vukasin0** [comment]
OK fair enough
