### ISSUE TITLE
Forced redirect on store request

### ISSUE THREAD

**Issue by shealan** [tymondesigns/jwt-auth#305]
I followed this tutorial https://scotch.io/tutorials/token-based-authentication-for-angularjs-and-laravel-apps and it works great.

JWT works as expected because when I use Auth::id() it gives me the correct user the token was generated for.

However, when I added a form request to my controller store method, or use controller validation it gives me a redirect page even when I pass the token. It seems to be a default Laravel one as apposed to a JWT token error. What am I missing?

**Comment by belisarh** [comment]
Because Laravel's Illuminate\Foundation\Http\FormRequest, which is extended by App\Http\Requests\Request, which is what you extend in your form request. So you might be right in your case about the 302 you might be getting. I have encountered this when trying to override how the form request handled the failed validation response in an API as I was writing a test for it. The case however, is that the redirect is triggered on a failed validation in the following method:

```php
    /**
     * Get the proper failed validation response for the request.
     *
     * @param  array  $errors
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function response(array $errors)
    {
        if ($this->ajax() || $this->wantsJson()) {
            return new JsonResponse($errors, 422);
        }

        return $this->redirector->to($this->getRedirectUrl())
                                        ->withInput($this->except($this->dontFlash))
                                        ->withErrors($errors, $this->errorBag);
    }
```

If the validation in your case should go through but still redirects I cannot think of a specific Laravel or JWT related reason. I am inclined to think validation is failing. Maybe forgot to change this:

```PHP
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return false;
    }
```

to

```PHP
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }
```

it is a small gotcha as it defaults to false when you create the request via artisan so it might trigger a validation error and redirect.

**Comment by shealan** [comment]
Thank you so much for offering a helping hand. Sadly this is something I have tried already. Setting the authorize() to false returns a response of "Forbidden" with an error 403. Setting to true gives the unexpected redirect response I mentioned in my original post. Does that narrow down things at all?

**Comment by chenkie** [comment]
I haven't encountered this myself before, sorry :(

Found a couple notes here, maybe some will be helpful: https://www.reddit.com/r/laravel/comments/32ms18/is_it_possible_to_disable_the_redirect_in_laravel/

**Comment by shealan** [comment]
Aha. That clears up exactly what's happening. Now I understand it more I can code accordingly. Thanks!
