### ISSUE TITLE
Token caching causing issues in acceptance test

### ISSUE THREAD

**Issue by cwhite92** [tymondesigns/jwt-auth#318]
I'm writing an acceptance test for an API endpoint. The test calls the same endpoint twice, with two different users. The cut-down version looks like this:

    public function testClientCanRequestAndAcceptFriendships()
    {
        $users = factory(\Lykit\Models\User::class, 2)->create();

        // Call #1
        $this->json('POST', $endpoint, $payload, ['Authorization' => JWTAuth::fromUser($users[0])]);

        // Call #2
        $this->json('POST', $endpoint, $payload, ['Authorization' => JWTAuth::fromUser($users[1])]);
    }

As you can see, I'm calling the first endpoint as the first user, and the second endpoint as the second user.

I've verified that the requests are sending the correct auth tokens, but jwt-auth is not parsing them from the requests correctly. The problem comes down to the `getToken()` method on `\Tymon\JWTAuth\JWTAuth`:

    public function getToken()
    {
        if (! $this->token) {
            try {
                $this->parseToken();
            } catch (JWTException $e) {
                return false;
            }
        }

        return $this->token;
    }

There seems to be some caching done here so that subsequent `getToken()` calls don't need to run the `parseToken()` method. This is causing jwt-auth to return the same auth token for my two test requests, and as such I'm not able to authenticate as the second user.

The high-level flow seems to be this:

1. Request 1 sent with auth token `auth.token.1`
2. Token parsed from request via `parseToken()` method and cached
3. Request 2 sent with auth token `auth.token.2`
4. The `parseToken()` method returns `auth.token.1` instead of `auth.token.2`

Now, why these two test requests aren't treated as independent is unknown to me, but this is using Laravel's default testing methods, so I think we need to make sure that it works correctly.

The `parseToken()` method doesn't strike me as particularly expensive, so I'm not sure why it needs to be cached to a class property? It seems the best solution to this is to just remove the `if (! $this->token)` conditional.

Would you accept a PR? :)

**Comment by cwhite92** [comment]
I've managed to work around this issue by doing the following between my two calls:

    $this->app = $this->createApplication();

This seems to basically reboot the framework (including jwt-auth) and it then successfully forgets the previous token and parses the new one from the second request.

While this workaround works, I still think it's important that the package works without it, since this definitely isn't the way Laravel's tests are intended to be written.

**Comment by tdhsmith** [comment]
Check out [this conversation](https://github.com/tymondesigns/jwt-auth/issues/206#issuecomment-151932258). I haven't done any followup yet, so I can't attest to the other solutions provided, but in general the issue has to do with how PHPUnit passes requests that makes multiple requests in a single test fail. As noted there, the `$this->refreshApplication()` command is a shorter form of the solution you found. And there might be improvements in 0.6.x that will allow us to sidestep the problem.

> The parseToken() method doesn't strike me as particularly expensive, so I'm not sure why it needs to be cached to a class property? It seems the best solution to this is to just remove the if (! $this->token) conditional.

The token gets saved on the class because then, in the controller, class methods don't need to reparse it. It makes the calls a lot simpler and keeps a good separation of concerns: parsing and authenticating actions stay in the middleware, while actions on the payload (e.g. accessing the subject's user model) stay in the controller.

**Comment by tymondesigns** [comment]
A recent change in the service provider might have solved this.
