### ISSUE TITLE
 Tymon\JWTAuth\Providers\JWTAuthServiceProvider is missing in 0.5.6 version

### ISSUE THREAD

**Issue by ashutoshjha88** [tymondesigns/jwt-auth#319]
Todaay i just update package through composer in my Laravel Project and i got this error

[Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Tymon\JWTAuth\Providers\JWTAuthServiceProvider' not found

**Comment by df-jablan** [comment]
Not missing, re-namespaced. 

Poor judgement doing so in a minor revision (0.5.6 vs 0.6.0). I'm sure many people's applications are now broken. :(

**Comment by yadakhov** [comment]
We got the same problem.. Rolling it back to 0.5.5 for now.

**Comment by tymondesigns** [comment]
Woops my bad.. I targeted the wrong branch!

Release now deleted

**Comment by tymondesigns** [comment]
@df-jablan not done intentionally. Will release revised version now

**Comment by tymondesigns** [comment]
Ok, version `0.5.6` released as per the master branch :sweat: 

Don't know what's with me today...

**Comment by ashutoshjha88** [comment]
@tymondesigns  Thanks buddy :+1:

**Comment by ashutoshjha88** [comment]
In 0.5.6 version  File Name: JWTAuth.php    Line No. 194
```php
if (! $token = $this->request->query($query, false)) {

```
I think you should use
```php
if (! $token = $this->request[$query]) {
```
to support for POST Method for passing token

**Comment by df-jablan** [comment]
@tymondesigns I did not mean to insinuate it was done on purpose. Apologies if taken as such. As they say, feces occurs. :)

**Comment by df-jablan** [comment]
@ashutoshjha88 I thought about your above request regarding capturing the POSTed value versus query string. While that's beneficial, it too is limiting.

Another approach to consider would be to provide a mechanism that injects a token retriever/resolver. This allows the consumer to decide from whence the token came. 

In either case, you should create a new issue since this one is closed.
