### ISSUE TITLE
JWT Authenticate to use guid instead of id

### ISSUE THREAD

**Issue by Vishal0203** [tymondesigns/jwt-auth#322]
Hi,

I changed the `identifier` configuration in jwt.php to `user_guid` a column in my Users table as I don't want to expose the `id` column. The jwt generated is fine and has correct value for the `sub`

However, the authenticate method uses `id` to authenticate, hence I always get `user_not_found` error. Any resolution for this?

**Comment by paulocoghi** [comment]
Maybe my issue #326 is related to this smaller one. One key aspect of my issue is that I am using a custom identifier (like you), the token is correctly generated, but authenticate methods fail to find the user from the same token JWTAuth generated before.

**Comment by jtthomas10** [comment]
You probably need to override the default User model to set the primary key.

Something like this in User.php:

```
    /**
     * The primary key for the model.
     *
     * @var string
     */
    protected $primaryKey = 'user_guid';
```

The identifier set in jwt.php is simply a name for the field that is in "sub" portion of the token.  I made the same assumption and it took me a day to sort through it, as I was also using a custom table and model not User.

Hope this helps.

**Comment by Vishal0203** [comment]
@jtthomas10 Thanks a lot Jeff, that worked. I had dropped the plan of hiding id from front end, you saved it.

**Comment by paulocoghi** [comment]
I will also try this solutions to see if it solves the mongodb problem ( informed in #326 ).

**Comment by tdhsmith** [comment]
Yes sorry I missed this issue somehow.

To give a deeper explanation, the `JWTAuth::authenticate` method relies on Laravel's `Auth::onceUsingId`, which will call `<UserModel>::find`. You can get this to use your custom identifier one of two ways:

1. Set your user model to use the custom identifier as its `$primaryKey`. Then all `::find()` lookups will check this field instead of the default `id`. (However if you rely on the default behavior elsewhere, this will have adverse effects.)

2. Create a custom provider implementing `Tymon\JWTAuth\Contracts\Providers\Auth`. You can take [the existing one for Illuminate](https://github.com/tymondesigns/jwt-auth/blob/develop/src/Providers/Auth/Illuminate.php#L55) and write a new `byId` function that looks returns the user using your custom identifier.

**Comment by paulocoghi** [comment]
@tdhsmith Thanks for the explanation!

**Comment by Vishal0203** [comment]
@tdhsmith I was thinking of following the 2nd step, but I thought it may break something, somewhere else. So are you going to add this enhancement?

**Comment by Vishal0203** [comment]
Changing the primary key is breaking my relations. I will go for second step.

**Comment by tdhsmith** [comment]
> I was thinking of following the 2nd step, but I thought it may break something, somewhere else

@Vishal0203 The provider I am talking about in step 2 is local to the JWTAuth package, so it should not affect anything else.

You will also need to configure JWTAuth to use your new provider [in the config](https://github.com/tymondesigns/jwt-auth/blob/develop/config/config.php#L134). Additionally if your new implementation of `byId` does not update `Auth`'s cached user, you will need to call something like `Auth::setUser` to update it. ([since the provider relies on that copy for the `user()` method](https://github.com/tymondesigns/jwt-auth/blob/develop/src/Providers/Auth/Illuminate.php#L68))

**Comment by Vishal0203** [comment]
@tdhsmith Thanks a lot for the detailed explanation. Was able to solve this with a custom `byId` implementation. Closing it now.
