### ISSUE TITLE
Long lived tokens as API keys

### ISSUE THREAD

**Issue by ValdasK** [tymondesigns/jwt-auth#327]
I'd like to create tokens for users as API keys, while still using same system for regular web authentication.

My plan is to create custom `audience` tags, and if token contains audience "api", skip expiration validation, but I cannot do that as `PayloadValidator` throws exception in any case if token TTL or global TTL is exceeded.

Any suggestions how to do this the other way?

**Comment by tdhsmith** [comment]
You're right, the validator is always going to trip on expired tokens, but it only checks the token's internal `exp` claim and not the current `ttl` settings. Therefore you could supply a custom (longer) `exp` claim for the API tokens when you create them.

```php
// version 0.5
$customClaims = [
    'aud' => 'api',
    'exp' => \Carbon\Carbon::now()->addWeeks(6)->timestamp
];
$apiToken = JWTAuth::fromUser($userId, $customClaims);
```

(I have no idea if that Carbon command is formatted correctly, but it's the general idea.)

**Comment by tdhsmith** [comment]
You should still implement an `aud` check in your middleware to make sure `api` tokens aren't being used for user-facing pages and vice versa.

Also I think v0.6 will require you to use the payload factory directly (because custom claims for the helper methods come directly from the `JWTSubject` interface).
