### ISSUE TITLE
User_not found ajax call

### ISSUE THREAD

**Issue by loreberti89** [tymondesigns/jwt-auth#358]
Hello, 
I'm using a Laravel Api and AngularJs frontend.
I have a problem with a middleware JWT.auth because if I do multiple asynchronous request from my frontend angularjs to backend api Laravel, sometimes (yes not always return error), return a 404 error "user_not_found" by middleware.

But doesn't return error in all request but in some.
I have no idea why this happens.

I have 4 ajax call from Angularjs Service with a promise and In back end I have a route group under middleware JWT.auth

Example.
I have 4 services calls tgat return a promise in my angularjs controller like:

User.findAll().then(.... )
Usergoups.findAll().then(...)
Workgroups.findAll().then(..)
Alert.findAll().then(...)

And on my backend laravale 5.1 I have a route group under jwt.auth middleware.

Route::group(['middleware'=>'jwt.auth'], function(){
   Route::get('usersFindall','userController@index');
   Route::get('alertFindall','alertController@index');
 Route::get('usergroupFindall','usergruopController@index');
 Route::get('workgroupFindall','workgroupController@index');
}

And sometimes one of calls return 404 error from middleware getusertoken middleware.
But not always.

Thank you!

**Comment by loreberti89** [comment]
I believe there is a Bug on middleware, because sometimes when there are multiple ajax call, middleware return 404, even if the calls are the same:
example:
if in my controller I do 10 calls equals:
 User.findAll().then(.... );
On some of this calls backend middleware return error 404, so I think it is a bug.

**Comment by tdhsmith** [comment]
What are you using for your database & auth user provider? Not to pass the blame, but without further evidence it seems more likely that you're having some sort of intermittent Auth/DB issues. It would be very strange to have errors within jwt-auth occurring randomly on multiple attempts with the exact same token, because the library is effectively stateless.

Due to #335, the master branch suppresses any exceptions `Auth` is throwing when you try to run `JWTAuth::authenticate(...)` (which is what `GetUserFromToken` uses). If you're still encountering this problem, try taking out the catch block [here](https://github.com/tymondesigns/jwt-auth/blob/master/src/Providers/Auth/IlluminateAuthAdapter.php#L44) and see if anything bubbles up?

**Comment by loreberti89** [comment]
Thanks for reply.
I'have "solved" the problem by not using middleware CheckToken,   and using a middleware CHECK that i've found in dev branch but using parsetoken.

mi middleware CHECK now is:
```php
 public function handle($request, \Closure $next){
        try {
            $this->auth->parseToken()->authenticate();

            } catch (\Exception $e) {

                return $this->respond('tymon.jwt.expired', "token_expired", 401);
            }

        return $next($request);
    }
```
