### ISSUE TITLE
Call to a member function parameter() on null

### ISSUE THREAD

**Issue by matiux** [tymondesigns/jwt-auth#361]
I use development branch to use package with doctrine and its private properties.
Since last update I get this error:
~~~
Call to a member function parameter() on null in /Project/vendor/tymon/jwt-auth/src/Http/TokenParser.php on line 87
~~~

This is the code that trown this error
~~~
        $httpRequest = new Request( [
            'token' => JWTAuth::fromUser($this->user)
        ]);

        \JWTAuth::parser()->setRequest($httpRequest)->hasToken();
        \JWTAuth::parseToken()->authenticate();
~~~

**Comment by tdhsmith** [comment]
The offending method is:
```php
    public function fromRoute()
    {
        return $this->request->route()->parameter($this->query, false);
    }
```
`Request` has no route available when you create it manually.

JWTAuth could probably throw a check in there to make sure route exists before calling that method, but it seems like an unusual use case. Is there a reason you're creating the request with `new`, rather than something like `Request::create(...)`? That kind of class instantiation usually doesn't work with Laravel due to all of the dependency injection and singleton management that the container normally handles...

**Comment by tdhsmith** [comment]
If you're doing this in testing, [Laravel has a number of helpers for HTTP requests](https://laravel.com/docs/5.1/testing#application-testing), like `$this->visit(...)`, `$this->{VERB}(...)`, `$this->call(...)`, etc...
