### ISSUE TITLE
Working without sessions

### ISSUE THREAD

**Issue by aejnsn** [tymondesigns/jwt-auth#392]
I am constructing a backend API (no need for sessions) that will communicate via JWT. I see in the classes within Tymon\JWTAuth\Providers\Auth that sessions are necessary in order to retrieve the user. However, JWT authentication is premised upon being stateless, yet this package is using sessions (state) in order to retrieve the current user.

**Comment by tymondesigns** [comment]
This package does not create any sessions, and is indeed stateless. It will be the default laravel auth system that it is creating any sessions.

You just need to remove all the session related middleware from the kernel

**Comment by aejnsn** [comment]
Okay. I understand the package is not actively using sessions. However, the structure of AuthInterface and its usages seem to be geared towards the use of sessions--at least insofar as relying on Guard or Sentinel to persist the current user somewhere within their objects' life cycle.

Furthermore, there has not been a release including the adapter for Sentinel since it was constructed...6 months ago. The latest release (0.5.6) does not include this adapter. So approaches like [this gist from iolson](https://gist.github.com/iolson/8a4c6d689a334f6de48e#file-sentinelauthadapter-php) are proliferating. This gist is the number one result on Google for "sentinel jwt auth", and the approach within the gist is completely incorrect. It is categorically incorrect to assume sessions with JWT authentication. I think if AuthInterface were structured differently, and thus the user object is to be persisted within the lifecycle of JWTAuth, the idea of implementations relying on sessions would become a non-issue.

**Comment by tdhsmith** [comment]
> However, the structure of AuthInterface and its usages seem to be geared towards the use of sessions--at least insofar as relying on Guard or Sentinel...

I don't want to speak for @tymondesigns, but I think the intent of relying on `Auth` was just to avoid reimplementing its credential operations, configs, and user providers. And the methods used are deliberately those that do not access or save anything to/from session. 

> I think if AuthInterface were structured differently, and thus the user object is to be persisted within the life cycle of JWTAuth, implementations relying on sessions would become a non-issue.

Do the lifecycles of `JWTAuth` and `Auth` differ in a meaningful way? I will readily admit I'm not an expert in the details of the Laravel container, but neither is going to outlive a particular request, so deciding whether `$user` is stored locally in one or the other seems minor...

That said, I agree there is room for a provider that has no auth dependency whatsoever. The project already has the beginnings of that for Laravel 5.2 with the direction `JWTGuard` is going, but something for Laravel 5.1 would be nice, especially since it's been guaranteed long-term support. I've been privately exploring this a little bit, but I haven't yet settled on how to deal with user contract stuff (for example, the default `EloquentUserProvider` needs a user that supports `newQuery`, but it'd be nice not to require Eloquent models specifically). If you have any suggestions/code, I'd love to see it!

**Comment by aejnsn** [comment]
I don't know if I expressed my idea as much as I griped about the gist with bad code in my last post. Auth is just one of Laravel's facades, and I am not proposing the wholesale removal of the reliance on an external authentication facility. I am proposing only the removal of the reliance upon the authentication facility (Guard/Senintel) to store the current user within its state/life cycle upon authentication. This can be achieved through restructuring the AuthInterface (its implementations and consumption patterns), and thus persisting the current user somewhere within JWTAuth's state.

It's not so minor in the grand scheme of writing defensive code. Because of AuthInterface's implementations, and how instances thereof are consumed, it allows the stateless nature of JWT to be violated. I think this would be a good improvement, and I definitely consider this an area where a JWT library should be opinionated. The more I think about it, this might not be a good fit for jwt-auth. I don't care for the project's branching and release history.
