### ISSUE TITLE
Seperate cache driver for token blacklist

### ISSUE THREAD

**Issue by pavankumarkatakam** [tymondesigns/jwt-auth#404]
I have many users so blacklisted token number is huge so i want to store this tokens in seperate redis instance rather than the default instance,It is very usefull to make configuration for changing the cache driver instance from the jwt.php config file other wise fallback to default cache driver set at cache.php config file.

**Comment by tdhsmith** [comment]
Hrm interesting question; I'm not sold yet on the added complexity. The library already has a few custom providers and they seem to confuse people as much as benefit them. :laughing: Why do you have so many blacklisted tokens?

Potential temporary solution: You could make your own 'intermediary' cache driver that returns your special redis instance when trying to access the `jwt` tag and the standard cache when trying to access any other tag.

**Comment by tdhsmith** [comment]
Okay I was confusing myself! :dizzy_face:

jwt-auth already provides this as an option in the configs. You simply have to create your own class implementing `Tymon\JWTAuth\Contracts\Providers\Storage`, and then set it in `jwt.providers.storage`.

Look at the default `Tymon\JWTAuth\Providers\Storage\Illuminate` class and then just modify it so that it only uses your special Redis instance.

**Comment by pavankumarkatakam** [comment]
Well it's  valid point but if you just make use of config for getting the disk and use of it. rather than writing the whole class again and again just give a option for users to have a storage disk. the code alrewady you has minial amount of change thats it. anayway it your call.

**Comment by tdhsmith** [comment]
Well it's up to tymon really. I understand it's annoying to have to create a whole class to change a line or two, but providing that option is the most flexible way to support the different cases that come up without having to include a vast array of configuration options.

Plus I'm not certain it's as easy as you say, because you're coming from the perspective of already having a specific cache driver. In the general case, won't we have to check whether the current cache driver even supports a connection change (or whatever your config is setting)? The common cache interface defines very few methods, and relying on duck-typing conditionals is prone to bugs in a framework as big and varied as Laravel.

**Comment by pavankumarkatakam** [comment]
@tdhsmith , Sorry I though you are the owner, okay its up to @tymondesigns .

> Plus I'm not certain it's as easy as you say, because you're coming from the perspective of already having a specific cache driver.

Its very simple just keep the driver option in the config and in the Illuminate/Storage constructor check the config storage disk option and change the code to 

    $this->cache=$cache->disk('configuationnoption'); 

Any way i will submit PR if possible.

**Comment by tdhsmith** [comment]
> `$this->cache=$cache->disk('configuationnoption'); `

Yes but this isn't a method on `Illuminate\Contracts\Cache\Repository` (or `...\Store` ) so there's no guarantee that a particular implementation will support it.

In fact I'm having a hard time finding any cache types with that method... this works for redis?

**Comment by pavankumarkatakam** [comment]
Of course, if config option is null then we can fallback to default in this case its not a breaking
 change or big change every on can continue.

**Comment by tymondesigns** [comment]
I think this is out of scope for this package tbh.

I am wary of adding too many config options that serve very specific use cases

**Comment by quevlu** [comment]
I have done an implementation using other connection string.

This is the storage class that use a different redis connection

`<?php

namespace App\Infrastructure\Redis;

use Illuminate\Support\Facades\Cache;
use Tymon\JWTAuth\Providers\Storage\Illuminate;

class BlacklistJwtStorage extends Illuminate
{
    public function __construct()
    {
        $this->cache = Cache::store(config('jwt.connection'));
    }
}
`

In jwt.php I've added the following config

`'connection' => env('JWT_CONNECTION'),`

In cache.php

`'jwt' => [
            'driver' => 'redis',
            'connection' => env('JWT_CONNECTION'),
            'lock_connection' => 'default',
        ],`

Finally, in database.php

`'jwt' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST'),
            'password' => env('REDIS_PASSWORD'),
            'port' => env('REDIS_PORT'),
            'database' => env('REDIS_JWT_DB'),
        ],`
