### ISSUE TITLE
Cannot reauthenticate with a different token

### ISSUE THREAD

**Issue by denaje** [tymondesigns/jwt-auth#42]
(FYI, I am testing things on your develop branch.)

In some of my tests, I login as two different users to make sure that things behave properly. I do this like so:

```php
$user = User::find($user_id);
$token = JWTAuth::fromUser($user);
// Store $token for use in subsequent requests
```

However, the second login never worked. I traced the issue to the `JWTAuth@getToken`:

```php
    /** 
     * Get the token
     *
     * @return boolean|Token
     */
    public function getToken()
    {   
        if (! $this->token) {
            try {
                $this->parseToken();
            } catch (JWTException $e) {
                return false;
            }
        }

        return $this->token;
    }
```

I'm sure there's a good reason for the outer if statement `if (! $this->token) {`, but this is what prevents multiple logins during the same session; if the token is already set, it doesn't reset it.

I worked around this issue in my own code by calling `JWTAuth::setToken($token)`, and this correctly updated the JWTAuth class with the new token for the second user. I'm not sure if this should be classified as a bug, feature, or wontfix, but I thought I'd bring it to your attention just in case.

**Comment by tymondesigns** [comment]
I see what you mean. 

It's because the `getToken()` method is not a basic getter, and adds the convenience of calling `parseToken()` to grab the token from the request if no token has been previously set.

I suppose this somewhat couples the http layer together with the actual nuts and bolts service layer and I will have a think about that...

On the other hand, I'm also thinking that it might be better to add a parameter that defaults to false, that would allow the consumer to choose whether they want to try and get the token from the request, or just return the token regardless.

Although I think that is separate from your case and you would be right to use `setToken()` anyway, since it doesn't look like you are using it in a traditional single token per http request manner ?

Anyways..you have definitely given me food for thought there.

Thanks.  I hope that wasn't confusing

**Comment by tymondesigns** [comment]
Ah just noticed you mentioned that this was in your tests. I guess the real world scenarios for this case are few and far between
