### ISSUE TITLE
Laravel 5.2 supported?

### ISSUE THREAD

**Issue by f0und3r** [tymondesigns/jwt-auth#461]
Hello guys, actually laravel 5.2 supported?

`PHP Fatal error:  Call to undefined method Closure::__set_state() in /bootstrap/cache/config.php on line 543`

**Comment by jfoliveira** [comment]
Could you post more details of how your environment/app is set up and which code block trigger this exception?

I'm running `jwt-auth` with Lumen 5.2 and it works fine, so chances are that Laravel 5.2 should is also supported.

**Comment by tdhsmith** [comment]
Yes there's an issue with the config files because they relied on closures at one point but then Laravel officially dropped support. (#147 and many others)

If you're on develop you'll just have to republish your vendor config for jwt-auth. If you're on master, just copy [the provider classnames from the develop branch's config](https://github.com/tymondesigns/jwt-auth/blob/develop/config/config.php#L112).

@tymondesigns - Laravel 5.1/5.0 doesn't need the closures right? It was just 4.2? Cause then this should probably change before that 0.5 bugfix release...

**Comment by tymondesigns** [comment]
@tdhsmith oops, yea I forgot about this.. (it is laravel 5.1) I might make 0.5.8 now to remove closures from the config

**Comment by tdhsmith** [comment]
Awesome! I just peeked at 0.5.7 and wondered that. :stuck_out_tongue:

**Comment by mtpultz** [comment]
An example implementation for Laravel 5.2.x using the JWTGuard can be found at [#513](https://github.com/tymondesigns/jwt-auth/issues/513#issuecomment-186087297)
