### ISSUE TITLE
Question: Is there a way to blacklist all previous tokens?

### ISSUE THREAD

**Issue by jaesung2061** [tymondesigns/jwt-auth#463]
How can I make it so all tokens made before a certain date/time are blacklisted?

**Comment by tdhsmith** [comment]
The server has no idea what tokens exist, so you can't blacklist any tokens you don't currently "have" in a given request.

- If this is a thing you think you will be doing _only in emergencies_, then just change the jwt secret key. This will effectively invalidate every token you issued with the old key, but it will also make them all unreadable and it's a rather extreme measure.

- If you think this is a thing you will be doing _once in a while_, consider storing a global `valid_after` value and then reject any token whose `iat` is before that time. This is an additional check you will need to implement on your own. (In the linked issues I talk about doing this at a per-user level.)

- If this is a thing you think you will be doing _often_, consider switching to a state-**ful** authentication system? JWTs are always going to be challenging to do these sorts of global operations on because they are designed to be self-contained and independent.

See #352, #310, #300, #296 for previous discussion. They're mostly about blacklisting all of a specific user's tokens, but they apply to this too.

**Comment by jaesung2061** [comment]
Thank you, checking them out now.
