### ISSUE TITLE
Refreshing tokens

### ISSUE THREAD

**Issue by mehrdaad** [tymondesigns/jwt-auth#480]
Hi, sorry for opening a new issue, but I couln't find an answer for my question.  
I've read [this](https://github.com/tymondesigns/jwt-auth/issues/301), [this](https://github.com/tymondesigns/jwt-auth/issues/186) but not getting totatally satisfied.  
I'm developing an api using Laravel 5.1 and jwt-auth 0.5.  
I'm facing several issues that makes me confused.  
First of all I wanna create a 'single-use' token approach which means in every request the token gets updated and previous token gets invalidated but as @tdhsmith indicates in [this](https://github.com/tymondesigns/jwt-auth/issues/186#issuecomment-147816841) comment this is package is not intended to be used for single-token approach.  
The second confusion is about concurrent requests, as been said there has been added PR but hasn't been published one yet.  
And also, If I want to create a multi-token approach, I can think of creating a route which neccesarily updates a token and invalidates the previous one,
So a client sends a request to a route if the client gets a token expired error status code(the code is made by convention) then it makes a request to refresh the token. but this approach really complicates the client workflow which I don't see appropriate.  
Do I miss sth or what is the soloution?  
And also @tdhsmith I would be glad to have a chat with you to clarify a few points for me. TNX!

**Comment by tdhsmith** [comment]
Sorry I don't have a lot of time right now, but to give you quick replies:

> @tdhsmith indicates in this comment this is package is not intended to be used for single-token approach.

No the package overall is perfectly fine for single-use tokens. The _middleware_ however imply a specific way of using the package which does not cover all cases, and may have unclear side effects if used in different way (like the one I mention there: using `GetUserFromToken` and `Refresh` together will end up rejecting _all_ expired tokens, regardless of the `refresh_ttl` setting).

I believe the documentation suggests that the provided middleware is just a starting point, but many people seem to believe they are the only way of using the package. You are encouraged to write your own that fit your needs.

> this approach really complicates the client workflow which I don't see appropriate

It is definitely a little more complicated, and I don't claim that it is better (or worse) than the alternative. It will depend on your project, and especially what your user behavior/timelines/security considerations are. 

Also some frameworks will make this behavior more straightforward; I've noted previously that in Angular it can be accomplished pretty easily with an http interceptor that resubmits the request after refreshing.

> as been said there has been added PR but hasn't been published one yet

I'm not sure which one you're talking about. I don't personally plan on implementing the grace period in 0.5 because I think that time would be better spent on 0.6 stuff. I _did_ submit a PR for the blacklist adding problem and I think @tymondesigns will release a 0.5.7 version with that soon.

If you're talking about the single-use middleware example, I haven't submitted that yet. :flushed: Should be on it in the next 48hrs though.

**Comment by tymondesigns** [comment]
0.5.7 is now released :smile:

**Comment by mehrdaad** [comment]
@tymondesigns with version 0.5.7 is it possible to assign a delay time for black listed tokens?

**Comment by sirago** [comment]
@tymondesigns I'm running 5.9 - is it possible to assign a delay time for blacklisted tokens? Without it, my Angular app is breaking.

**Comment by murillobarata** [comment]
Resolved?
