### ISSUE TITLE
Token in method POST, MethodNotAllowedHttpException in RouteCollection.php line 219:

### ISSUE THREAD

**Issue by juniormc** [tymondesigns/jwt-auth#483]
I'm trying to send token via a query string with method POST. 
You can send that? or should it send ?

**Comment by w0rd-driven** [comment]
Do you need it to be sent via a query string or could it be part of the POST body? Including a key (of any sort, be it JWT or api) is a bad security practice because most web servers log query strings in access logs. Conveniently I can't find the link where I saw this as I've been doing way too much research on all of this lately. It should still be allowed though.

Having said that, I do believe the exception points to [this stackoverflow answer](http://stackoverflow.com/a/33179455/134335). I know if I set the route as a post and use a get it doesn't work, that you see "Token in..." or any other information is kind of misleading.


Hopefully this helps but if not things like the Laravel version and the jwt-auth version would be helpful, as well as any example code you could provide. I don't think this applies to this package though but is an underlying Laravel problem.

**Comment by tdhsmith** [comment]
Yeah, it's very unlikely this has to do with the jwt-auth package, which doesn't use `MethodNotAllowedException`. More likely your routes are misconfigured somewhere.

Also I agree with @w0rd-driven, query strings are a little more "visible" than headers or bodies. However the jwt-auth parser does support them out of the box so you should have no problems there.

**Comment by tymondesigns** [comment]
indeed nothing to do with this package, you have a routing issue somewhere
