### ISSUE TITLE
JWT + Entrust

### ISSUE THREAD

**Issue by amilgaul** [tymondesigns/jwt-auth#484]
Hi Tymon,

Is there a chance that Entrust can integrate to jwt? jwt for authentication and Entrust for role based permission? How can i do it?

Thanks.

**Comment by tdhsmith** [comment]
I am not familiar with Entrust, but it doesn't _look_ like there should be any major issues or overlap. Just use jwt-auth to get your user model from a token, and then call your role/ability checks upon that user?

**Comment by tymondesigns** [comment]
Or even better imo, just use Laravel's Gate Authorization functionality https://laravel.com/docs/5.2/authorization :smile: 

Then you could do things like:

```php
if (Auth::user()->can('update-post', $post)) {
    // do things
}
```

**Comment by tdhsmith** [comment]
:+1:

I'm not sure how I'd gone this long without learning about `Gate`... :disappointed:

**Comment by tymondesigns** [comment]
@tdhsmith haha 💥😀

**Comment by amilgaul** [comment]
@tdhsmith I have a small problem regarding role/ability checks. When I trying to check if the user has a role of administrator using entrust middleware, the request has always thrown a 403 status or access denied. It seems that I was login as guest only even though the user has an administrative privilege. Please refer to the code below:

Route::group(['middleware' => ['role:administrator']], function(){
....
});

and when I used this code:

if(Auth::user()->hasRole('administrator'))
{
// logic
}

i got these error.

**Call to a member function hasRole on null**

What did i miss?

**Comment by tdhsmith** [comment]
Laravel Auth doesn't automatically know how to parse tokens, so your `Auth::user()` is null. You have to call something to parse the token from the request and store its user in Auth. There are several options, but I'd recommend using middleware because it is likely simpler:

- If you only want these pages accessible by those with valid tokens, you can wrap the route in the `GetUserFromToken` (0.5) / `Authenticate` (0.6) middleware.

- If you want these pages accessible by guests and/or invalid token holders as well (for example if you want to return results to both kinds of users, but still need a role check to affect which results are displayer), then you should use the `Check` (0.6) middleware, which is effectively the same as the previous, but *will not quit when the token is missing/invalid/expired*.

In the former case, your Auth's user will always be set. In the latter, it will sometimes be null.

**Comment by tdhsmith** [comment]
`Check` isn't available in 0.5, but you can approximate it with your own, something like: 


```php
public function handle($request, Closure $next)
{
    if ($token = $this->auth->setRequest($request)->getToken()) {
        try {
            $this->auth->authenticate($token);
        } catch (Exception $ex) {
            unset($ex);
        }
    }
    return $next($request);
}
```

**Comment by amilgaul** [comment]
@tdhsmith I prepared your first suggestion and I want to know on how I can store the parse token in user Auth. It will be more easy for me to use the role/ability checks of entrust. Can you show me an example of storing parse token to user Auth. I'm just a beginner in Laravel and jwt and I really want to achieved this goals.

**Comment by tdhsmith** [comment]
Calling `JWTAuth::authenticate()` will already do that for you because, with the default settings, it in turn calls `Auth::onceUsingId($id)`, [which will set it internally](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Auth/SessionGuard.php#L488).

If you're just looking for a manual way to set it, you can use `Auth::setUser($user)`.

There are plenty of other ways, too. Check out [the official docs on authentication](https://laravel.com/docs/5.2/authentication) for some examples...

**Comment by amilgaul** [comment]
@tdhsmith Thanks for the help it's working now. The only thing I miss is the jwt.auth middleware to include it on route.

**Comment by zhaohehe** [comment]
get user model by JWTAuth::parseToken()->authenticate(),
and use JWTAuth::parseToken()->authenticate()->can('user.get.profile')  to get result.
