### ISSUE TITLE
class Class Tymon\JWTAuth\Providers\Storage\Illuminate does not exist

### ISSUE THREAD

**Issue by aixeiger** [tymondesigns/jwt-auth#530]
I made an application with laravel and jwt, following the instructions here in the wiki of jwt-auth, I have this error when I try to Authenticate:

`ReflectionException in Container.php line 738:
Class Tymon\JWTAuth\Providers\Storage\Illuminate does not exist`

The configuration is the same as the wiki

`public function postLogin(Request $request){

    	$credentials = $request->only('email','password');

    	try{
    		if(!$token=JWTAuth::attempt($credentials)){
    			return response()->json(['error'=>'invalid credentials'], 401);
    		}
    	} catch(JWTException $e){
    		return response()->json(['error' => 'could not create the token'], 500);
    	}

    	return response()->json(compact('token'));
    }`

**Comment by fevaldez** [comment]
Use this as jwt.config :
[https://github.com/scotch-io/laravel-angular-token-authentication/blob/scotch/config/jwt.php](url)

They already mentioned the solution in one of the threads but I can't remeber which one.

**Comment by tdhsmith** [comment]
Actually it was just a temporary bug with 0.5.8, it's already been fixed in [0.5.9](https://github.com/tymondesigns/jwt-auth/releases/tag/0.5.9).

The long standing "config closures" issue that I believe @fevaldez is referring to is also fixed, so now there should be no need to override any config settings... unless you're actually configuring something. :wink:

**Comment by fevaldez** [comment]
Thank you @tdhsmith, I figured there was a new version to be released soon. :D
