### ISSUE TITLE
Add the possibility to store token into response's cookie

### ISSUE THREAD

**Issue by michelecurletta** [tymondesigns/jwt-auth#629]
What do you think about adding the possibility to choose from a token sent via Json (as is) to a token stored into a response's cookie?
According to [this article](https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage/) both are valid alternatives with different pros/cons.

**Comment by tymondesigns** [comment]
I'll take a look into it, thanks for the link

**Comment by aleemb** [comment]
This would be useful (parser would be nearly identical to `InputSource` parser). Cookies are persistent which brings some nice benefits. browser-based clients can be setup with zero configuration because the server response would set the token in the cookie. It would make token refreshes less painful. More importantly, the browser-based clients would require zero configuration as cookie-based tokens would work out of the box.

**Comment by aleemb** [comment]
I saw the cookie parser was committed, thanks very much for that.

However, this parser should be considered dangerous as it opens up a CSRF attack vector and should not be used in production.  I had meant to comment earlier but I shied away from this approach for this reason.

My motivation for cookie based tokens was because it works entirely through existing HTTP mechanisms meaning browser-based clients would not need to any additional work to enable JWT tokens (which authorization headers, input fields or query strings all require). The other motivation was that because of this token refreshes require no additional work.
