### ISSUE TITLE
Unable to override claim

### ISSUE THREAD

**Issue by djoks** [tymondesigns/jwt-auth#648]
Hello I have tried to override **exp** with the following code:

```
$credentials = $request->only('email', 'password');
        $claims = ['exp' => (int) Carbon::now()->addYears(99)->getTimestamp()];

        try {
            // verify the credentials and create a token for the user
            if (!$token = JWTAuth::attempt($credentials, $claims)) {
                return response()->json(['code' => 401, 'message' => 'Invalid Email / Password'], 401);
            }
        } catch (JWTException $e) {
            // something went wrong
            return response()->json(['message' => 'could_not_create_token'], 500);
        }
```

However when I check the token it always defaults to the default value set in my **.env** file.

**Comment by akanevsky** [comment]
What does the `.env` file have to do with the `exp` value in your token? Also, `getTimestamp()` in your code will return `false`. This is due to the year 2038 problem (https://y2038.com/). The year you are setting your date to cannot be represented by as 32-bit Unix timestamp. The value will become `0` after it is cast to an `int`. I haven't tested this, but I doubt that the package will allow you to have an `exp` value of `0` in your token.

**Comment by JPeer264** [comment]
It is the same for me. I am working with Lumen 5.2. This is my simplified code:

```php
$credentials = $request->only('email', 'password');
$customClaims = ['exp' => 1514764800, 'foo' => 'bar'];

$token = $this->auth->attempt($credentials, $customClaims);

return response()->json(compact('token'));
```

I followed the guides but when I decode my token, everything is set to default as well.

**Comment by djoks** [comment]
@akanevsky Unfortunately that does not seem to be the issue, at least when I tested it it wasn't, the value always sets to the default value in my jwt.php file which means that that config file overwrites all other custom claims.
