### ISSUE TITLE
Can't canonicalize query: BadValue unknown operator: $id

### ISSUE THREAD

**Issue by raghu2333** [tymondesigns/jwt-auth#733]
Hi,
 i am getting "Can't canonicalize query: BadValue unknown operator: $id" while using JWTAuth::parseToken()->toUser()

my database is mongodb
in route.php
        $api->version('v1',['middleware' => 'jwt.auth'],function($api){
       $api->get('getuser','App\Http\Controllers\Auth\AuthController@getUser');
       }
in AuthController.php
    public function getUser()
    {
        return JWTAuth::parseToken()->toUser();
     }

in User Model
     use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
     class User extends Eloquent
    {
    protected $primarykey   =   "_id";
    protected $collection   =   "users";
  }

in config/jwt.php
   'identifier' => '_id',

i am able to insert the user but not able to authenticate..
So Please help me out in solving the issue.. thanks in advance

**Comment by tdhsmith** [comment]
Hrm. The error is coming from MongoDB, but I don't know why.

If you're using a different model class things can get a little unusual. Sometimes you have to write a custom user provider for jwt-auth, _but_ in this case I wouldn't think that was necessary (because `Jenssegers\Mongodb\Eloquent\Model` extends the Eloquent model and still supports the `where` method in the same way).

What happens if you do this instead?

```php
// in AuthController
public function getUser()
{
    $knownUserID = 1; // set to a user ID you know exists
    return User::where('_id', $knownUserID)->first();
}
```

That should be the underlying call that `toUser` is making. Knowing if it fails or not will help us know if the problem is inside jwt-auth, or elsewhere.
