### ISSUE TITLE
JWTException when trying to use RS256 algorithm

### ISSUE THREAD

**Issue by righter** [tymondesigns/jwt-auth#763]
In order to successfully sign and verify tokens using RS256, I had to override a few methods in `Tymon\JWTAuth\Providers\JWT\Namshi`.
Here's what I have set up:

- I'm working from a fresh Laravel 5.2 installation
- I installed tymon/jwt-auth, 1.0.0-alpha.2
- JWT_PUBLIC_KEY=/tmp/jwt_auth/pubkey.pem
- JWT_PRIVATE_KEY=/tmp/jwt_auth/privkey.pem
- JWT_ALGO=RS256

I'm authenticating a user like this:
```php
    public function authUser(JWTAuth $jwt)
    {
        return $jwt->attempt(['email' => 'foo', 'password' => 'password']);
    }
```

which results in the following error:
```
JWTException in Namshi.php line 61:
Could not create token: openssl_pkey_get_details() expects parameter 1 to be resource, boolean given
```

Looking at the tests on the develop branch, the NamshiTest is using `file_get_contents` to get the file contents into a resource.

To keep changes out of the vendor directory, I created a new provider which extends `Tymon\JWTAuth\Providers\JWT\Namshi`. This allowed me to override the methods I needed and I was able to successfully authenticate users and receive/verify signed tokens.

**Comment by tdhsmith** [comment]
So what changes did you make?

Looking at Namshi's source, it _seems_ like you should be able to pass in a file reference. The `PublicKey` signers have [a `getKeyResource($key)` function](https://github.com/namshi/jose/blob/7.1.0/src/Namshi/JOSE/Signer/OpenSSL/PublicKey.php#L57) that retrieves a resource from a string. Hrm...

**Comment by tdhsmith** [comment]
Wait I think I see a potential issue: `getKeyResource($key)` relies on `openssl_pkey_get_public($certificate)` which, [according to PHP docs](http://php.net/manual/en/function.openssl-pkey-get-public.php), requires certificate to be one of:

> 1. an X.509 certificate resource
> 2. **a string having the format `file://path/to/file.pem`.** The named file must contain a PEM encoded certificate/public key (it may contain both).
> 3. A PEM formatted public key.

I just checked in the interactive shell, and that `file://` prefix in (2) is totally required for strings. The function returns `false` without it. So try adding that maybe?

**Comment by righter** [comment]
I thought I tried `file://` in my `.env` but it was late and I was tired. I'll take another look.

Here's what I did to get signed keys coming back:
```php
<?php
namespace App\Providers\JWT;

use Tymon\JWTAuth\Providers\JWT\Namshi;

class NamshiOverride extends Namshi
{

    /**
     * Get the public key used to sign tokens
     * with an asymmetric algorithm.
     *
     * @return resource|string
     */
    public function getPublicKey()
    {
        return $this->getFileContents(parent::getPublicKey());
    }

    /**
     * Get the private key used to sign tokens
     * with an asymmetric algorithm.
     *
     * @return resource|string
     */
    public function getPrivateKey()
    {
        return $this->getFileContents(parent::getPrivateKey());
    }

    /**
     * Get the passphrase used to sign tokens
     * with an asymmetric algorithm.
     *
     * @return string
     */
    public function getPassphrase()
    {
        return $this->getFileContents(parent::getPassphrase());
    }

    /**
     * Ensure we return a file resource
     *
     * @param $key
     * @return resource
     */
    private function getFileContents($key)
    {
        return is_resource($key) ? $key : file_get_contents($key);
    }
}

**Comment by righter** [comment]
I gave `file://` a shot with no luck. Here are the different things I tried in the `.env` config to no avail.

```php
JWT_PUBLIC_KEY=/tmp/jwt-auth/pubkey.pem
JWT_PUBLIC_KEY='/tmp/jwt-auth/pubkey.pem'
JWT_PUBLIC_KEY=file://tmp/jwt-auth/pubkey.pem
JWT_PUBLIC_KEY='file://tmp/jwt-auth/pubkey.pem'
```

**Comment by djordn** [comment]
Hi.
I could only fix this adding `file_get_contents` in my `config.php`
Here's my code:

```
/*
 * This file is part of jwt-auth.
 *
 * (c) Sean Tymon <tymon148@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

$file =  config_path('server.key') ;
$rs = file_get_contents($file);
```

and my JWT_SECRET :

`'secret' => env('JWT_SECRET', $rs ),`

**Comment by tdhsmith** [comment]
Ok I dug into this in a little bit, and I have successfully managed to get file path strings to work, with the following config:
```php
'keys' => [
    'public'     => 'file://../public.pem',
    'private'    => 'file://../private.pem',
    'passphrase' => 'password'
],
```

I think the issues are a lot of little quirks about the process:

- [`file://`](http://php.net/manual/en/wrappers.file.php) can lend itself to easy mistakes. If you want absolute paths, you need to start it with a hard-to-see third slash `file:///`. And you have to keep PHP's working directory in mind for relative paths -- for the average Laravel project, that's gonna be `<project>/public`, so you'll need to move up a level. (@righter maybe one of these was your issue?)
- OpenSSL is very strict about the PEM format. You can't pass in plain pub key files like those `ssh-keygen` creates that start with "ssh-rsa". In fact, I couldn't even get _PEM files_ created by `ssh-keygen` to be recognized. I think it's something with the ANS1 encoding (which is sort of proprietary I guess) because OpenSSL always complains about the tags or the heading structure or somesuch. So it may be that you can only use keys generated by `openssl`. (@djordn since your file has the extension .key, this might be your problem?)
- Like many PHP built-ins, the openssl functions have to be polled for their error messages, using `openssl_error_string()`. This combined with the fact that namshi/jose isn't coded very defensively, means it's a little hard to get any info about what's wrong. I'm planning to submit a PR to namshi in the next day or so to update the messaging there.

That all said, I think the solutions you two used are both perfectly acceptable, and considering how finicky it all is, I wouldn't fret too much about it. 😛

**Comment by righter** [comment]
Thanks @tdhsmith! From my prospective, this issue is resolved unless you want to keep it open.

**Comment by tdhsmith** [comment]
Feel free to close (I don't have the perms). I'll be tracking the JOSE improvements in their PR since that isn't specific to this lib.

**Comment by djordn** [comment]
Hello!
Thanks for explanation.
@tdhsmith, where am I suppose to set this key config?

```
'keys' => [
    'public'     => 'file://../public.pem',
    'private'    => 'file://../private.pem',
    'passphrase' => 'password'
],
```

When I set in `config/jwt.php` it is ignored.

**Comment by tdhsmith** [comment]
Are you on v0.5? The setting (and ability to use public key systems) only exists in 1.0.

**Comment by tdhsmith** [comment]
Also for reference to anyone visiting this thread, the patch landed in namshi/jose as of their version 7.2.0, so if you update to that you should start seeing error messages explaining any key issues.

**Comment by djordn** [comment]
You're right.
I'll give a shot after update my project.
Thanks!

**Comment by djordn** [comment]
Hello!
Now its everything ok.
Thanks for spent time.
I hope to contribute to project soon.

**Comment by JCarlosR** [comment]
Hi. Sorry if my next doubt is too strange, but I am new using JWT.
I'm trying to authenticate a user in Firebase using the credentials of my Laravel app.
According with this tutorial: https://firebase.google.com/docs/auth/server?hl=es
I have to create a JWT with custom parameters. I did that, and the token is generated.
But the last step is change the algorithm to RS256. **To use RS256 is neccesary to have always two passwords?**
I just have a private_key from the firebase console.
