### ISSUE TITLE
Interoperability with standard Laravel Auth functions

### ISSUE THREAD

**Issue by trisc** [tymondesigns/jwt-auth#77]
To make your plugin more of a drop in replacement for those who use `Auth::check()` and `Auth::user()` throughout their codebase, would it not be possible to have your middleware call `Auth::login($user)` if the token is successfully parsed?

Additionally on routes where hard authentication isn't required (i.e. it's acceptable for public or authorised access, it simply returns more detail for an authenticated user vs public access), would it be possible to have a third middleware method that simply does a soft check for a valid token. Which, if authenticated calls Auth::login($user), but if not, doesn't automatically return an unauthorised response and allows your controller function to continue. This would allow `Auth::check()` and `Auth::user()` to function as expected. Either that or at the very least a convenience function like the Auth functions that don't throw exceptions when you simply want to check if a current session has an authenticated user, or access that user.

Also would it be correct to assume that doing the above would allow use of the `be($user)` call in Laravel unit testing, as you can keep the standard Auth calls throughout your application.

If these already exist, are a bad idea for any reason, or I'm misunderstanding how to best make use of JWTAuth as conveniently as `Auth::check()` and `Auth::user()` let me know.

**Comment by bbrink68** [comment]
`JWTAuth::parseToken()->authenticate();`  or `JWTAuth::parseToken()->toUser();`
Either will return the User model to you I believe.

**Comment by RMFogarty** [comment]
Not sure if this is the best way to do it, for Laravel 5 in the
EventServiceProvider Boot function I listen for the valid token event and
call the login function as you suggested:

Event::listen('tymon.jwt.valid', function($event)
{
Auth::onceUsingId( \JWTAuth::toUser( \JWTAuth::getToken() )->id );
});

This will allow you to continue to use the Auth::check and Auth::User
functions.

**Comment by tymondesigns** [comment]
@trisc The plugin isn't really intended to be a drop in replacement for Laravel's Auth. It merely utilises it to retrieve the authenticated user via some of the methods it provides.

I am only using the methods that are stateless and do not invoke any session handling. e.g. [`once`](https://github.com/illuminate/auth/blob/master/Guard.php#L254-L264) and [`onceUsingId`](https://github.com/illuminate/auth/blob/master/Guard.php#L497-L502). JWT's do not require the overhead of session based authentication.

[This class](https://github.com/tymondesigns/jwt-auth/blob/laravel-5/src/Providers/Auth/IlluminateAuthAdapter.php) is where I call the aforemetioned methods. As you can see, the User is set on the object and passed through from Laravel, so it should be possible to call `Auth::user()` in the same request. 

Also since `Auth::check()` only [checks for the presence of a user object](https://github.com/illuminate/auth/blob/master/Guard.php#L107-L110), then you should be able to use that aswell.

@RMFogarty You should be able to use the methods without that code as mentioned above.
Also just FYI, the authenticated user is passed through with the event, so you could do:

```php
Event::listen('tymon.jwt.valid', function($user)
{
    Auth::setUser($user);
});
```

Hope that helps

**Comment by diaspar** [comment]
@tymondesigns is there a way to have the auth user analyzed after the middleware finishes?

\Tymon\JWTAuth\Middleware\BaseMiddleware

Doing this at the controller level: $user = JWTAuth::parseToken()->authenticate() , does not run again all the token verification process?

**Comment by tymondesigns** [comment]
@diaspar I will look into adding another middleware that only verifies the token is present and valid

Thanks
