### ISSUE TITLE
The token expired after 60 minutes

### ISSUE THREAD

**Issue by trangchuvn** [tymondesigns/jwt-auth#777]
Hello guys!
I know that we can custom the "ttl" time in the jwt.php file. but the problem is when i'm working on my application, the token is still expired. i thought when i send a request to the server, the time of token should be refreshed. i have research and found the way is "jwt.refresh". but when i use "jwt.refresh", the token will be changed when i send a request to the server. i thought it only refresh the time? i cann't get and store new token  in front-end application for each request to the server
I'm using laravel 5.2, jwt-auth: 0.5.*. This is my route in laravel

```
Route::group(['middleware' => ['jwt.auth','jwt.refresh']], function() {
        /* Component */
        Route::get('searchComponent', 'ProductController@searchComponent');
});
```

Can you give me any solution?
Best thank

**Comment by tdhsmith** [comment]
> i have research and found the way is "jwt.refresh". but when i use "jwt.refresh", the token will be changed when i send a request to the server. i thought it only refresh the time?

That time--specifically, `exp` the timestamp of expiration--isn't stored on the server; it's stored inside the token. So in order to change the amount of time left, you have to change the token.

Since tokens are considered _immutable_, you can't modify them after they are made. You have to create an entirely new copy, which is exactly what `jwt.refresh` is doing.

>  i cann't get and store new token in front-end application for each request to the server

Then don't use the refresh middleware everywhere. (Though I am curious why you aren't able to store new tokens...)

**Comment by trangchuvn** [comment]
thank for your reply. store new tokens is ok. but with many async requests i think it's impossible. right? Can you tell me what should i do in this case please?

**Comment by renanpro03** [comment]
@trangchuvn You can check at your front-end if the response was "error":"token_expired" if so, you can call a method to refresh it and store the new token...

**Comment by tdhsmith** [comment]
>  but with many async requests, i think it's impossible. right? 

For particularly dense requests, the 1.0 branch provides a "grace period" where old refreshed tokens stay valid for a short time before being blacklisted.

If you're doing "refresh-as-needed" (what @renanpro03 suggests) you can just wait until you see an error response, request a new token, and then resend all of the errored responses that accumulated since then with the new token.

**Comment by trangchuvn** [comment]
@renanpro03 thank for your help, but maybe it's not a solution for me.
@tdhsmith i think it's better if i can increase the time out of the token for each request. if i can do it, it would be great
but at the moment, the "grace period" is also a another solution for me. but can you tell me how can i get the 1.0 branch by composer please?
i'm using laravel 5.2. Can you help me to change this composer
```
"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "tymon/jwt-auth": "0.5.*"
    },
```

**Comment by warriorkitty** [comment]
I had the same problem and removing `bootstrap/cache/config.php` did the trick.
