### ISSUE TITLE
It didn't work when installed kbwebs/multiauth

### ISSUE THREAD

**Issue by Crazyweed** [tymondesigns/jwt-auth#779]
it didn't work when I installed the package kbwebs/multiauth. how do i set the config to make it works.

**Comment by tdhsmith** [comment]
How doesn't it work? What's wrong? For example, tell us what you did to try to make it work, and if you're seeing an error, please post the stack trace.

**Comment by radicalloop** [comment]
@Crazyweed  You have to implement your own Authentication Provider instead of default in jwt-auth.
You can check this [gist](https://gist.github.com/radicalloop/163fb808618c0054baa47435ea18974c) where I'm using "user" provider (which is added in **auth.php 'multi-auth'** option).

After that you need to change **'auth'** option of **'providers'** in **jwt.php** file.
In my case: `'auth' => 'App\Providers\Auth\IlluminateAuthAdapter',`.
