### ISSUE TITLE
Changing Authentication Provider

### ISSUE THREAD

**Issue by Mylo-92** [tymondesigns/jwt-auth#781]
Good Day,

I just wanted to know if it is possible to change the 'default' authentication provider ```'auth' => 'Tymon\JWTAuth\Providers\Auth\IlluminateAuthAdapter',``` in jwt.php to something else. For example, I am trying to implement the package with [Adldap2](https://github.com/Adldap2/Adldap2-Laravel) but kinda noob and not too sure how to proceed. I tried changing the value of the 'auth' key to ```'Adldap\Laravel\AdldapAuthServiceProvider'``` but to no avail. Should it be something else perhaps?

Any advice will be greatly appreciated.

Kind Regards,

**Comment by tdhsmith** [comment]
> I just wanted to know if it is possible to change the 'default' authentication provider `'auth' => 'Tymon\JWTAuth\Providers\Auth\IlluminateAuthAdapter'`, in jwt.php to something else. For example, I am trying to implement the package with Adldap2 but kinda noob and not too sure how to proceed.

Yep, it's totally possible. In fact, that's why it's set up that way in the first place! Otherwise all of those functions could live inside the jwt-auth core, but with them as swappable providers, you can more easily change how jwt-auth behaves without actually editing this package's code.

>  I tried changing the value of the 'auth' key to `'Adldap\Laravel\AdldapAuthServiceProvider'` but to no avail. Should it be something else perhaps?

Yeah, it's going to be a class that you have to write. A "_service_ provider" in Laravel is a specific kind of class that runs when the application starts and registers/configures application components. A "provider" _in general_ is vaguer; in this case it's an adapter that connects jwt-auth to your authentication system. So connecting this to that package's service provider probably won't be what it's looking for.

Luckily the class you need to make is quite simple. Just look at what [`IlluminateAuthAdapter`](https://github.com/tymondesigns/jwt-auth/blob/master/src/Providers/Auth/IlluminateAuthAdapter.php) does for the default auth. You just need to create the 3 methods there that do corresponding actions (two kinds of log-in and one method that retrieves the current user, if any) in the package you're using. Then plug that class' name into the config and you should be set!

**Comment by tdhsmith** [comment]
Actually I should back up to the first question -- are you sure you need to change the auth provider? I'm not familiar with Adldap2/Adldap2-Laravel but a cursory glance seems to indicate that it might use Laravel's built-in auth system. (It's definitely adding a new _user provider_, but that's just a piece that the auth "guard" interacts with.)

**Comment by Mylo-92** [comment]
Honestly, I am not too sure. Using ```JWTAuth::attempt($credentials)``` the token gets generated and user is authenticated. However, when I try to retrieve the authenticated Active Directory user via ```$user->adldapUser``` where the Adldap Model is bound to the the Laravel Model, it returns a null value. Using the regular ```Auth::attempt($credentials)```, no token is generated, just a boolean returned in this case true and null for the bound user. I will, try to implement your suggestion and report back.

Kind Regards

**Comment by tdhsmith** [comment]
> Using `JWTAuth::attempt($credentials)` the token gets generated and user is authenticated.

Hrm it sounds like you might not need the auth provider then. Usually it's only necessary when calls like `JWTAuth::attempt`and `JWTAuth::authenticate` completely fail and error out. If they're working, then jwt-auth is successfully connecting with Laravel's auth management.

> Using the regular `Auth::attempt($credentials)`, no token is generated, just a boolean returned in this case true and null for the bound user. 

This is to be expected. On v0.5, this library does not change the behavior of the `Auth` facade, so it'll keep on not knowing anything about tokens. If you want to do something with tokens, use the `JWTAuth` facade methods.

If you're expecting `Auth::attempt` to work with Adldap, then it's probably something with your Adldap settings, because jwt-auth would change pretty much nothing there.

**Comment by Mylo-92** [comment]
Did some more digging/testing and eventually it all made sense. In order to integrate Adldap, laravel's default authentication driver has to be replaced with the packages own e.g 'adldap'. And as JWTAuth makes use of laravel's built-in auth system as you said, that "wrapper" exists for it as well. So yeah, kinda embarrassing but I guess it was overthinking on my part. Thank you for your help though, made it all clearer.

**Comment by martimarkov** [comment]
@Mylo-92 How did you solve this exactly?
