### ISSUE TITLE
Invalid signature after upgrade

### ISSUE THREAD

**Issue by boedy** [tymondesigns/jwt-auth#783]
I upgraded from 0.5.9 to 1.0.0-alpha.2.

1.0.0-alpha.2 can't verify signatures generated by 0.5.9.

The following config is unchanged:
- JWT_SECRET
- ttl
- refresh_ttl
- algo
- required_claims

Can anyone confirm?

Need to upgrade without forcing people to login again.

**Comment by tdhsmith** [comment]
The version of [namshi/jose](https://github.com/namshi/jose) (the underlying library that handles the token signatures) does change between those branches, from ^5.0 to ^7.0. It's possible something in their implementation changed. Previously there had been an issue where that library was off-spec, and the fix invalidated all sigs (since every signature was being generated slightly wrong). That change occurred between v0.5.3 and v0.5.4 though, so unless you hadn't updated in a long time, it wouldn't be that specific issue.

Of course, it's also possible something changed in _this_ library. But the fact that signature verification fails limits it to a fairly small area.

I'll try to reproduce when I get the chance.

When you say JWT_SECRET is unchanged, I assume you mean `jwt.secret` still points to `env('JWT_SECRET')` and your env file's `JWT_SECRET` is the same?

**Comment by boedy** [comment]
Yes,  my env file's JWT_SECRET is the same.

**Comment by jbardnz** [comment]
Hey 

Just to chime in I ran into this exact same issue a couple of days ago. Specifically for me I was trying refresh tokens generated in 0.5.9 but it wasn't able to validate them at all. 

Maybe their is a workaround were I can manually verify a 0.5.9 token with 1.0.0?

**Comment by tdhsmith** [comment]
Hrm I haven't been able to reproduce this yet, but I've only done a small example. At the very least, HS256 seems to be consistent between JOSE v5 & v7.

Can you guys share a token & key that validate in 0.5.9 but not in 1.0.0? (I'd temporarily change your secret to something irrelevant like 'password'...)

**Comment by boedy** [comment]
Here is token which is generated by 0.5.9 (with a different secret):

> eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3NTY4am00MGoiLCJpc3MiOiJodHRwOlwvXC9pbnN0b3JlLmRldlwvYXV0aGVudGljYXRpb24iLCJpYXQiOjE0NjgwMDI3MDAsImV4cCI6MTQ2ODAwNjMwMCwibmJmIjoxNDY4MDAyNzAwLCJqdGkiOiI2NTc2NTUxN2EzMjU5YWE3ZjFmNjFhNmY3MjExNGQ0NCJ9.Foq2oIUPQF_ZJ9CZyoItagyCnW9fZuAW1zWyTY78bkA

I've currently extended the refresh middleware to support both versions as an migration strategy until the majority of users has acquired a new token. Not Ideal.

**Comment by chmoelders** [comment]
Hey!

I ran into the same issue. After a little research I'm sure the problem originated in (namshi/jose)[https://github.com/namshi/jose], commit [do not escape slashes in json_encoding of jwt components](https://github.com/namshi/jose/commit/04c5a8bbe79e8f4ca3b21cb2e122f9ee97396f92).
When I revert this commit, jwt-auth 1.0.0-alpha.2. is able to validate tokens generated with 0.5.9.

My assumption is that tokens generated with 0.5.9 aren't compatible with 1.0.*, please correct me if I am wrong.

**Comment by chmoelders** [comment]
It looks like we need an update-strategy.
Any ideas?
