### ISSUE TITLE
token generated but cant validate token.

### ISSUE THREAD

**Issue by mehranhadidi** [tymondesigns/jwt-auth#784]
Hi

I generated a token without using user object. 

```
$mobile = $request['mobile'];

$payload = JWTFactory::make(['sub' => 123456]);
return $token = JWTAuth::encode($payload);
```

but when i want to access a route that is protected i get an error:

```
{
  "message": "Unable to authenticate with invalid token.",
  "status_code": 401
}
```

but my generated token has valid signature on jwt.io

i think there should be a bug. what should i do?

**Comment by mehranhadidi** [comment]
@tdhsmith thanks for your replay. i understand it. my bad. but, if i want to separate these two from each other? i mean is there any way to create a token & pass it to user over an api but dont create a user? 

i have a situation that i have some guest users that want to use the mobile app. they should see stuf (so they need a valid token) but they should not cannot do anything moderating (like, comment etc.) until they register as a user. 

in this situation i dont have a user record to assing to that. 

what do you suggest?

thanks for your replay again :+1:

**Comment by jsdecena** [comment]
I second on this. I am also getting `Unable to authenticate with invalid token.` error. I am only providing an API Key and Secret to the app that wants to access a resource on my server so there is no `User` attached to it. Anyway, in the [docs ](https://github.com/tymondesigns/jwt-auth/wiki/Creating-Tokens#creating-a-token-based-on-anything-you-like), it says that you can create a token from anything you like right? 

Any help on this issue is appreciated. TIA!

**Comment by usmanhafeez147** [comment]
@tdhsmith I used your method to generate token, but its giving an error for me "should not be called statically"
