### ISSUE TITLE
Include the Cookie Parser in the Abstract Service Provider

### ISSUE THREAD

**Issue by yorchv** [tymondesigns/jwt-auth#785]
By Default the Cookie parser is not included in the Service Provider neither for Laravel nor Lumen. This removes the option to handle the token via cookie, leaving outside the benefits of security that the cookie offers.

There are many ways to make the cookie behavior outside the provider, but now that I know that is included in the library but not used, I should consider that is restored as part of the regular parser.

On the other side, I have created a custom provider that handles Cookies and Auth Header. Feel free to use it.

https://gist.github.com/yorchv/851013b95a45e3c15bcfa883816db316

**Comment by xFlatlinex** [comment]
I agree, having it on the cookie is better, and since the Parser is there, why not just add it to the chain?
@yorchv I ended up essentially doing the same thing, it is a good and simple option.
But I think it would be useful if one could configure the chain through a config file, just to give a simpler option.
