### ISSUE TITLE
composer version not updated?

### ISSUE THREAD

**Issue by qurius** [tymondesigns/jwt-auth#788]
I installed jwt-auth yesterday upon `composer update` but I did not get JWTGuard etc and other files are also different. Is this version not registered with composer?. Sorry if I am mistaken. I am new to jwt-auth/composer

**Comment by mattisdada** [comment]
JWTGuard as an example is only available on the master branch, or the "in development" part. Composer generally works with tags (you can set it to use branches instead, but I'd recommend against that). You most likely have the latest stable version of the codebase.

**Comment by qurius** [comment]
If we use this(develop) branch would it break any code with dingo api?

**Comment by tdhsmith** [comment]
> JWTGuard as an example is only available on the master branch, or the "in development" part. Composer generally works with tags (you can set it to use branches instead, but I'd recommend against that). You most likely have the latest stable version of the codebase.

Just to clarify, the **0.5.x** release series (the "old" version) is currently the *master* branch and the **1.0.x** release series (the "new" version with `JWTGuard` etc) is currently the *develop* branch.

What version you get is going to depend on what version you specified in your original install. For example if you selected `^0.5` or `~0.5` or `0.5.*`, composer won't update you past the "major version number bump" to 1.0.

The matter is a little more complicated because there isn't a stable release of 1.0 yet, so your minimum stability setting must be at `dev` or `alpha` for composer to accept the new versions. Otherwise they will just be ignored. (You can also set the stability level per-package with version flags like `1.0@dev`)

If you want to learn more, check out [the official docs on composer versioning](https://getcomposer.org/doc/articles/versions.md) or [this great interactive demo](https://semver.mwl.be/#?package=tymon%2Fjwt-auth&version=%5E1.0&minimum-stability=dev).

> If we use this(develop) branch would it break any code with dingo api?

I haven't verified it personally, but Dingo's most recent dev release, v1.0.0-beta3, seems to have added support. (cf dingo/api@c3d95614d86da80)  Versions before that will likely break.
