### ISSUE TITLE
check() can't distinguish different guard

### ISSUE THREAD

**Issue by Master-Xia** [tymondesigns/jwt-auth#795]
In **config/auth.php**, I have two guards:

```
        'api' => [
            'driver' => 'jwt',
            'provider' => 'users',
        ],

        'admin_api' => [
            'driver' => 'jwt',
            'provider' => 'admins',
        ],
```

I got token with:
`$token = Auth::guard('api')->attempt($credentials)`
And I check it with:
`Auth::guard('admin_api')->check()`
But it should be true.
where is wrong?

**Comment by tradzero** [comment]
+1

**Comment by tradzero** [comment]
@tymondesigns

**Comment by tymondesigns** [comment]
This should be resolved, since we now include a hashed model claim (`prv`) into the token by default. This ensures that the subject that originally created the token is the only one that can consume it.

Although you shouldn't use the `check()` method (right now). Use `Auth::user()` & `Auth::guest()` instead.

I might tweak the check method to support this actually...
