### ISSUE TITLE
How do not use the default guard, because the default Guard does not require token Api?

### ISSUE THREAD

**Issue by spc324** [tymondesigns/jwt-auth#815]
How do not use the default guard, because the default Guard does not require token Api?
I set the jwt config file user='App\Member', but the default is to match the Default under the Guard Auth.php

**Comment by mtpultz** [comment]
Hi @spc324, this sounds more like you might not understand guards, and the issue doesn't actually reside in the jwt-auth package.  I'll attempt to give you a quick idea of guards in Laravel 5.2+, but since this isn't an issue with jwt-auth afterwards could you please close this issue.

In 5.2 if you look at your AuthenticatesUsers you see a method getGuard(), which checks for a member variables $this->guard or returns null, which is used by `Auth::guard($this->getGuard())...` .  If null is returned then in auth.php the default guard will be used, which if you haven't changed it will be `web`.  If in your AuthController you add the member variables `$guard = 'api'` then getGuard() will use it and return `api`, which will be passed to `Auth::guard($this->getGuard())` the same way, but instead use the `api` guard not the default.  

So to quickly recap what is passed to `Auth::guard(...)` dictates what guard will be used, otherwise it will use the default.
