### ISSUE TITLE
{error: "token_invalid"} when using jwt-auth behind ec2 load balancer

### ISSUE THREAD

**Issue by hesomWela** [tymondesigns/jwt-auth#850]
When I setup my API behind a ec2 load balancer with 2 servers, I start getting some random token_invalid errors when its trying to call endpoints on the different boxes. Is there any setup I need to do to enable multi-server?

**Comment by sleenen** [comment]
make sure the server time is the same on the different servers. 
Consider this:

1. request token call goes to server 1
2. a second api call with that newly created token goes to server 2

Now if the server time on server 2 is a few seconds behind server 1, to server 2 the token would seem to be created in the future and will then decline the token.

**Comment by sleenen** [comment]
Actually, that was 1 part of the problem. Now I am facing another problem:

I have 2 servers, when I do a login call to server 1 to retrieve a new token and then use that token with a request to server 2, I get a Token invalid exception, with the message "Token Signature could not be verified."

I don't understand why this happens, since the settings (secret, algorithm etc) are all the same?!?

**Comment by Hesesses** [comment]
did you ever solve this?

**Comment by hesomWela** [comment]
@Hesesses Yes, I was able to solve the issue by setting up a NTP service on the 2 machines.

**Comment by Hesesses** [comment]
Did the same and works for me also 👍
