### ISSUE TITLE
Conflict with google apiclient

### ISSUE THREAD

**Issue by agneshoving96** [tymondesigns/jwt-auth#902]
This package conflicts with the google apiclient package because it uses an old version of phpseclib.

**Comment by andrefcgoncalves** [comment]
Same problem here.

**Comment by ipridham** [comment]
Run the following commands
`composer remove tymondesigns/jwt-auth  `
`composer require namshi/jose:6.1`
then edit your composer.json to read
` "namshi/jose": "6.1 as 5.0.2"`

then `composer require tymondesigns/jwt-auth  `

You should be able to install google apiclient package now, although i'm not sure previous tokens generated will work due to the changes to namshi/jose

**Comment by vrubiella** [comment]
Hello, I have a lot of problems too.This versions works fine for me:
```json
    "require": {
        "php": ">=7.0",
        "laravel/framework": "5.3.*",
        "kozz/laravel-guzzle-provider": "6.0",
        "google/apiclient": "2.1.*",
        "namshi/jose": "7.2.2",
        "tymon/jwt-auth": "1.0.0-alpha.3"

    }
```
