### ISSUE TITLE
Help using this package in a web app architecture

### ISSUE THREAD

**Issue by photoart-mtlwebdev** [tymondesigns/jwt-auth#92]
Hi everyone,

I'm not reporting an issue here but looking for some help implementing this feature in my specific architecture. Nothing fancy but I'm just having trouble to picture how/where to store the generated token on client side, my clients being browsers, PHP web apps and iOS native app.

I know this isn't the place to discuss this but I was thinking maybe I could find the proper audience for this matter. If someone reads this and is willing to answer a few questions on a side discussion to clarify a few things for me, I would be really grateful.

Here is my scenario:
I'm building a REST API that will be handling the business logic (might switch to Lumen for this). "Clients" will authenticate against this API. At the moment, I'm successfully getting the token and passing it back on every single request using Postman.

I have no trouble getting how a SPA or native iOS app would then send the token at every request as they "directly" communicate with the API, but I have a hard time seeing how the PHP web app (Laravel 5) would do it.

In the case of a web app, the browser is sending a request to the web app whose then relaying the request to the API.
On first user's authentication, the API sends a token back to the web app, but this token has to be sent and stored somewhere in the browser (Local/Session Storage or cookie) I know these 2 options have security concerns. Also an iOS app would handle cookies badly but a regular (not SPA) would prefer cookies as requests wouldn't be fired by any JavaScript (Local storage wouldn't be accessible in that case).

My question is: does the web app need to store the token somewhere in session ?
I need the web app to send the token on each request to the API, but it feels like the browser also needs to send that token to the web app on each request.

I'm quite confused about this "2 step" operation and can't figure out who should keep the token and where.

If one of you has the solution or at least could get me on tracks, it would be just great.

Thanks a lot.

**Comment by devmark** [comment]
JWT-Auth is similar than session but that can solve more problems like cors.
so if we use jwt-auth, we have to store token on client side for each request what u said.

the token will expiry(ext) automatically by api server.

**Comment by photoart-mtlwebdev** [comment]
Hi @devmark, 

thanks for your input. You're right about the short expiry of the token.

What I meant was: should I store the token in a specific cookie in the browser ? Or should I keep it in the web app ?

What I ended up doing is storing the token in session. This way the relation is stateless between the API and the web app, and statefull (session cookie) between the web app and the browser.
Now the token isn't directly exposed to the web client (it still is though for the iOS app) and the "VerifyCsrfToken" middleware helps securing the session cookie.

Let's take this example:
token expiry: 10min
session expiry: default (24min if I recall)

First question:
I have 2 options there: refresh token on every single call (maybe overkill), or check its expiry on every request and refresh it if it is about to expire within the next minute. What do you think ?

Second question:
As the token is deleted from session but might still be valid, do I need to invalidate the token when the session expires ? It seems to me that most of the time the token will have expired by the time the session has, right ?
Anyway, I didn't find any efficient way to detect when session expired, apart from storing sessions in a database (or Redis), and then use a CRON to invalidate tokens that belong to an expired session in the database table.

Your opinions are more than welcome :-)

Thanks.

**Comment by pfazzino** [comment]
If you're not doing a SPA and want the token to go up the wire on every request you will have to store it in a cookie or have it included in all urls as a query param. 

If you're using jwt for sessions, one suggestion is go the whole way and make the session the token and remove any notion of server side session state. Include any session data you need directly in the token (encrypting if necessary). This way your session expiry IS your token expiry. This solves your other problems like keeping the token and the session in sync, storing sessions in REDIS, etc..

One thing you will need to tackle is normally session expiry is a sliding window/idle time. An easy way to achieve this is do what you suggest and issue a new cookie/jwt on every request. That way you automatically get idle session expiry based on the ttl in the token.

**Comment by photoart-mtlwebdev** [comment]
Hi @pfazzino,

It looks like I've missed your message...I just saw it a few minutes ago.
Thanks for your suggestions.

I still can't see how you would "make the session the token". Where would you store this token on the server if not in session ? I never intended to use jwt for sessions, I just wanted to avoid storing the token in the browser so I left it in the server session. This way the Laravel web app became the "client".

Thanks for your input.

**Comment by pfazzino** [comment]
Why do you need to store the token in session? One of the points of jwt is that it's stateless. By storing it in session you immediately tie to a server or at least some form of backend storage. Also why are you concerned about storing the token in the browser? Are you putting senstivie data in the token? If you are you should encrypt it otherwise I'm not sure where the concern is. 

When I say make the session the token I mean remove all notion of backend session (session_start) or laravel sessions, etc.. You have a token in which you can store whatever data you wish (payload size and security permitting) so why do you need anything else on the backend. This is very similar to what laravel does if you set the session driver to cookie.

**Comment by photoart-mtlwebdev** [comment]
I get what you mean by losing the stateless part of the concept. But as the webapp then acts as a client to the API, it is exactly the same as having an iOS app storing the token and sending it directly to the API, isn't it ?

I didn't store the token in session initially but then I had to store it in the browser (cookie), send it to the web app, that would send it to the API. It didn't seem "clean" to me but maybe I was wrong.
Is this what you would do ?

**Comment by pfazzino** [comment]
I'm not seeing the connection between storing the token in the session and storing it in the browser as a cookie. 

For a browser based client, you generally have two models, either you're building a javascript heavy/single-page-app (SPA) webapp, in which case all of the html is delivered on first load and from there on it's all client side js making ajax calls (http://www.toptal.com/web/cookie-free-authentication-with-json-web-tokens-an-example-in-laravel-and-angularjs). For this model you don't need to store the token as a cookie as you're in control of the request so can pass it is an authorization bearer token. This also means you can choose local storage if you prefer. If your serving up web 'pages' and each request is a full page request, then you need to store the token as a cookie so that the browser will automatically submit on every request (for forms you can override this behavior but let's keep it simple for now).

For your iOS app you can treat it like a javascript app, send it in the header and store it wherever you like on the local device using whatever iOS storage api's you prefer.

Going back to your original question, there's no need for any separate session expiry in these models. You don't need session state on your backend (unless I'm missing part of the picture). Set your token expiry to whatever you want to use as your session expiry (e.g. 24mins in your case) and rotate the token on every request. That way the user will have to remain idle for 24mins before the token will become invalid.
