### ISSUE TITLE
how to use content-type:json 

### ISSUE THREAD

**Issue by ahmedonee** [tymondesigns/jwt-auth#948]
how to make request with content-type:json instead of application/x-www-form-urlencoded

**Comment by johannesschobel** [comment]
Dear @ahmedonee ,

shouldn't it work "right out of the box" with `application/json`? Plase try using `Postman` (extension for google chrome) in order to test your request. Using this application (Postman) you are able to set the respective request-headers needed (e.g., `Content-Type = application/json' ).

Can you report on this issue again? If it does not work _out of the box_, I can send you code from my `authentication()` method..

Cheers
