### ISSUE TITLE
[Question]How to add an extra parameter on login query

### ISSUE THREAD

**Issue by Mirdrack** [tymondesigns/jwt-auth#952]
I would like to be able to add an extra parameter on the query to attempt login  

For example:  
```
        $credentials = $request->only('email', 'password', 'guild_id');
        try {
            if (! $token = $this->jwt->attempt($credentials)) {
                return $this->respondWithUnauthorized('Invalid Credentials');
            }
        } catch (JWTException $e) {
            return $this->respondWithInternalError('Could not create token');
        }
```

Should I create my own **Auth Adapter** or what is the best approach to face this because right know im getting this query exception:  
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'guild_id' in 'where clause' (SQL: select * from `users` where `email` = user@mail.com and `guild_id` = 1 limit 1)
```

If anybody needs more information just let me know
Thanks in advance

**Comment by johannesschobel** [comment]
Hey @Mirdrack ,

does your `users` table in the database provide a `guild_id` field? Because the SQL error you posted says, the column is unknown (e.g., not present)..
Can you give an update on this issue?

If you do not have a `guild_id` field, you need to write a specific `migration file` in order to append this field to the `users` table. For more information see this link here: [Laravel Migrations](https://laravel.com/docs/5.1/migrations#creating-columns) (I assume, you are using Laravel)

Cheers

**Comment by Mirdrack** [comment]
Thanks for the quickly answer and yes you are right my class map wasn't updated and that is the reason why my field was not present  
Sorry for this but its good to know that the attempt function keeps the same functionality as in Laravel  
Please consider this as resolved and thanks for your time
